# Roadmap

1. Preprocessing con VAD para eliminar ruidos o momentos de silencio.
2. Ventanas con solapamiento.
3. Extracción de características (OpenSMILE, Librosa), según fuentes: Prosody, voice quality, spectral features (MFCC). O modelos como Wav2Vec.
4. Modelización y evaluación.

5. Usar LLMs multimodales para analizar la entrada de audio directamente.

In [1]:
import torch
import os
import librosa
import soundfile as sf
import numpy as np
import pandas as pd
import torchaudio
from transformers import Wav2Vec2Processor, Wav2Vec2Model
from tqdm import tqdm
from huggingface_hub import login

from sklearn.pipeline import Pipeline, make_pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import StratifiedGroupKFold, cross_val_predict
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score, balanced_accuracy_score, recall_score
from xgboost import XGBClassifier
from imblearn.ensemble import BalancedRandomForestClassifier

/home/ethe/miniconda3/envs/tfg/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

# Load and preprocessing

In [2]:
#VAD model
model, utils = torch.hub.load(repo_or_dir='snakers4/silero-vad', model='silero_vad', force_reload=True)
(get_speech_timestamps,save_audio,read_audio,VADIterator,collect_chunks) = utils
sampling_rate = 16000

Downloading: "https://github.com/snakers4/silero-vad/zipball/master" to /home/ethe/.cache/torch/hub/master.zip

In [3]:

def apply_vad(input_dir, output_dir, sampling_rate = 16000, threshold = 0.2, speech_pad_ms=250):

    for subject in os.listdir(input_dir):

        for act in os.listdir(os.path.join(input_dir, subject)):

            audio_path = os.path.join(input_dir, subject, act)
            subject_act = os.path.basename(audio_path).split('.')[0]
            wav = read_audio(audio_path, sampling_rate=sampling_rate)

            speech_timestamps = get_speech_timestamps(wav, 
                                        model, 
                                        sampling_rate=sampling_rate,
                                        threshold = threshold,
                                        speech_pad_ms = speech_pad_ms,
                                        )
            
            if len(speech_timestamps) > 0:
                out_dir = os.path.join(output_dir, subject)
                os.makedirs(out_dir, exist_ok=True)
                save_audio(os.path.join(out_dir, f"{subject_act}.wav"), collect_chunks(speech_timestamps, wav), sampling_rate=sampling_rate)

            else:
                print('VAD failed on', audio_path)

apply_vad(input_dir='./data/original/', output_dir='./data/vad_applied')

/home/ethe/miniconda3/envs/rl_env/lib/python3.11/site-packages/torchaudio/__init__.py:178: UserWarning: The 'bits_per_sample' parameter is not directly supported by TorchCodec AudioEncoder.
  return save_with_torchcodec(

VAD failed on ./data/original/h7j3/h7j3_Counting1.wav
VAD failed on ./data/original/h7j3/h7j3_Counting3.wav
VAD failed on ./data/original/h7j3/h7j3_Math.wav
VAD failed on ./data/original/h7j3/h7j3_Stroop.wav

# Windowing

In [8]:
import os
import numpy as np
import soundfile as sf
import librosa

def save_audio_windows(input_dir, output_dir, window_size=5.0, overlap=0.0, sampling_rate=16000):
    """
    Splits each audio file into fixed-length windows and saves them.

    input_dir structure:
        input_dir/subject/activity.wav

    output_dir structure:
        output_dir/subject/activity/window_0.wav
    """

    stride = window_size * (1 - overlap)

    for subject in sorted(os.listdir(input_dir)):
        subject_dir = os.path.join(input_dir, subject)

        if not os.path.isdir(subject_dir):
            continue

        for act_file in sorted(os.listdir(subject_dir)):
            if not act_file.lower().endswith(".wav"):
                continue

            audio_path = os.path.join(subject_dir, act_file)
            activity = os.path.splitext(act_file)[0]

            y, sr = librosa.load(audio_path, sr=sampling_rate)
            duration = librosa.get_duration(y=y, sr=sr)

            out_act_dir = os.path.join(output_dir, subject, activity)
            os.makedirs(out_act_dir, exist_ok=True)

            start = 0.0
            window_id = 0

            while start + window_size <= duration:
                end = start + window_size

                start_sample = int(start * sr)
                end_sample = int(end * sr)

                y_window = y[start_sample:end_sample]

                out_path = os.path.join(out_act_dir, f"window_{window_id}.wav")
                sf.write(out_path, y_window, sr)

                window_id += 1
                start += stride

            if window_id == 0:
                print(f"No complete windows for: {audio_path}")

        print(f"{subject} done.")

    print("All audio windows saved.")

In [9]:
save_audio_windows(input_dir='./data/vad_applied', output_dir='./data/5s_0overlap')

2ea4 done.
2hpu done.
2z7d done.
45lx done.
4e8r done.
4woj done.
5f7t done.
6g6y done.
6k5f done.
71i5 done.
7h5u done.
7m3c done.
No complete windows for: ./data/vad_applied/8g4y/8g4y_Math.wav
No complete windows for: ./data/vad_applied/8g4y/8g4y_Stroop.wav
8g4y done.
No complete windows for: ./data/vad_applied/8i4i/8i4i_Counting3.wav
No complete windows for: ./data/vad_applied/8i4i/8i4i_Math.wav
No complete windows for: ./data/vad_applied/8i4i/8i4i_Stroop.wav
8i4i done.
9j3o done.
No complete windows for: ./data/vad_applied/9t6n/9t6n_Counting2.wav
9t6n done.
9txq done.
a1k9 done.
b2l8 done.
b9w0 done.
bfl5 done.
c3m7 done.
chdf done.
ctzy done.
cxj0 done.
No complete windows for: ./data/vad_applied/d4n6/d4n6_Stroop.wav
d4n6 done.
e5p4 done.
g7r2 done.
g9j5 done.
No complete windows for: ./data/vad_applied/h7j3/h7j3_Counting2.wav
h7j3 done.
h8r2 done.
h8s1 done.
i9t9 done.
iqyg done.
No complete windows for: ./data/vad_applied/j9h8/j9h8_Counting3.wav
j9h8 done.
k2v7 done.
k67g done.
kkf5 done.
kycf done.
m8g5 done.
p9i3 done.
No complete windows for: ./data/vad_applied/qw5t/qw5t_Counting1.wav
No complete windows for: ./data/vad_applied/qw5t/qw5t_Counting2.wav
No complete windows for: ./data/vad_applied/qw5t/qw5t_Counting3.wav
No complete windows for: ./data/vad_applied/qw5t/qw5t_Stroop.wav
qw5t done.
r3zm done.
r5s8 done.
t6v9 done.
tmvd done.
u3v9 done.
uymz done.
v8mh done.
w2t5 done.
wssm done.
x1q3 done.
y8c3 done.
y9z6 done.
All audio windows saved.

# Paralinguistic audio features extraction using LIBROSA:

In [5]:
import pandas as pd

def extract_features_from_audio(y, sr):
    features = {}

    # Energy / loudness
    rms = librosa.feature.rms(y=y)[0]
    features["rms_mean"] = np.mean(rms)
    features["rms_std"] = np.std(rms)

    # Zero-crossing rate
    zcr = librosa.feature.zero_crossing_rate(y)[0]
    features["zcr_mean"] = np.mean(zcr)
    features["zcr_std"] = np.std(zcr)

    # MFCCs
    mfcc = librosa.feature.mfcc(y=y, sr=sr, n_mfcc=13)

    for i in range(13):
        features[f"mfcc_{i+1}_mean"] = np.mean(mfcc[i])
        features[f"mfcc_{i+1}_std"] = np.std(mfcc[i])

    # Pitch / F0
    f0, voiced_flag, voiced_probs = librosa.pyin(
        y,
        fmin=librosa.note_to_hz("C2"),
        fmax=librosa.note_to_hz("C7")
    )

    valid_f0 = f0[~np.isnan(f0)]

    if len(valid_f0) > 0:
        features["pitch_mean"] = np.mean(valid_f0)
        features["pitch_std"] = np.std(valid_f0)
        features["pitch_min"] = np.min(valid_f0)
        features["pitch_max"] = np.max(valid_f0)
    else:
        features["pitch_mean"] = 0.0
        features["pitch_std"] = 0.0
        features["pitch_min"] = 0.0
        features["pitch_max"] = 0.0

    # Voiced ratio
    features["voiced_ratio"] = np.mean(voiced_flag) if voiced_flag is not None else 0.0

    # Pause / low-energy ratio
    if len(rms) > 0:
        silence_threshold = np.percentile(rms, 25)
        features["low_energy_ratio"] = np.mean(rms < silence_threshold)
    else:
        features["low_energy_ratio"] = 0.0

    return features

def extract_audio_window_features(windows_dir, output_csv, sampling_rate=16000):
    """
    Iterates through saved audio windows and extracts acoustic features.

    windows_dir structure:
        windows_dir/subject/activity/window_0.wav
    """

    rows = []

    for subject in sorted(os.listdir(windows_dir)):
        subject_dir = os.path.join(windows_dir, subject)

        if not os.path.isdir(subject_dir):
            continue

        for activity in sorted(os.listdir(subject_dir)):
            activity_dir = os.path.join(subject_dir, activity)

            if not os.path.isdir(activity_dir):
                continue

            for window_file in sorted(os.listdir(activity_dir)):
                if not window_file.lower().endswith(".wav"):
                    continue

                window_path = os.path.join(activity_dir, window_file)

                window_id = int(
                    os.path.splitext(window_file)[0].replace("window_", "")
                )

                y, sr = librosa.load(window_path, sr=sampling_rate)

                features = extract_features_from_audio(y, sr)

                rows.append({
                    "subject": subject,
                    "activity": activity.split('_')[1],
                    "window_id": window_id,
                    "subject_activity": activity,
                    **features
                })

    df = pd.DataFrame(rows)
    df.to_csv(output_csv, index=False)

    print(f"Saved features to: {output_csv}")
    print(f"Total windows processed: {len(df)}")

    return df

In [6]:
audio_features = extract_audio_window_features(
    windows_dir="./data/5s_0overlap",
    output_csv="audio_features_5s_0overlap.csv",
    sampling_rate=16000
)

SystemError: CPUDispatcher(<function _viterbi at 0x7f54ec4a9b20>) returned a result with an exception set

In [8]:
df_features = pd.read_csv('audio_features_5s_0overlap.csv')
df_features

,subject,activity,window_id,subject_activity,rms_mean,rms_std,zcr_mean,zcr_std,mfcc_1_mean,mfcc_1_std,...,mfcc_12_mean,mfcc_12_std,mfcc_13_mean,mfcc_13_std,pitch_mean,pitch_std,pitch_min,pitch_max,voiced_ratio,low_energy_ratio
0,2ea4,Counting1,0,2ea4_Counting1,0.024353,0.020337,0.105705,0.072654,-356.31620,151.180020,...,-11.756525,7.607572,-5.105567,10.692554,176.133509,23.820995,146.832384,241.301496,0.796178,0.248408
1,2ea4,Counting1,1,2ea4_Counting1,0.028559,0.028854,0.125883,0.074720,-355.78770,146.941590,...,-1.005276,8.748446,-6.677289,7.742668,154.764206,7.597938,135.425885,169.643191,0.573248,0.248408
2,2ea4,Counting1,2,2ea4_Counting1,0.015406,0.017756,0.143368,0.121097,-402.19458,151.004400,...,-7.368523,8.041126,-5.682947,6.806932,161.598019,7.368555,145.986692,179.730700,0.407643,0.248408
3,2ea4,Counting1,3,2ea4_Counting1,0.018954,0.014357,0.252301,0.206833,-350.57910,137.426790,...,-6.566986,9.046530,-5.721100,8.508836,179.229013,10.754735,164.813778,212.505992,0.331210,0.248408
4,2ea4,Counting1,4,2ea4_Counting1,0.019945,0.022307,0.196426,0.163529,-384.57385,140.356980,...,-6.529265,7.016305,-5.260243,8.912770,176.025027,22.264465,150.264428,222.556277,0.509554,0.248408
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3086,y9z6,Stroop,5,y9z6_Stroop,0.005253,0.003730,0.174096,0.148333,-416.65552,26.029297,...,4.814869,6.066178,-0.803817,4.724341,288.951181,11.438753,272.420799,314.742105,0.490446,0.248408
3087,y9z6,Stroop,6,y9z6_Stroop,0.005614,0.003532,0.137512,0.080529,-411.51510,21.044626,...,1.782596,5.066959,-1.944231,3.988037,289.444627,19.222600,249.810974,329.627557,0.675159,0.248408
3088,y9z6,Stroop,7,y9z6_Stroop,0.005724,0.005155,0.188439,0.141175,-413.65952,22.627660,...,2.444980,6.029319,-1.771422,5.470934,291.377745,17.634666,246.941651,327.729042,0.515924,0.248408
3089,y9z6,Stroop,8,y9z6_Stroop,0.005175,0.003828,0.190187,0.147750,-413.93054,24.514980,...,1.723448,5.382573,-2.693949,5.017823,281.451714,16.369882,263.141147,329.627557,0.515924,0.248408
3090,y9z6,Stroop,9,y9z6_Stroop,0.008048,0.006040,0.162520,0.114633,-392.80023,49.853348,...,3.168118,7.315823,-1.401565,8.284023,309.367753,17.526360,278.788334,361.543738,0.738854,0.248408

# Per task aggregation:

1. Feature level aggregation:

In [49]:
def task_aggregation(df_audio, gt):
    df = df_audio.copy()

    # Remove non-feature columns
    id_cols = ["subject", "activity", "window_id", "subject_activity"]
    feature_cols = [c for c in df.columns if c not in id_cols]

    # Make sure features are numeric
    df[feature_cols] = df[feature_cols].apply(pd.to_numeric, errors="coerce")

    # Aggregate window-level features to task-level
    agg = df.groupby("subject_activity")[feature_cols].agg(["mean", "std", "max"])
    agg.columns = [f"{feat}_{stat}" for feat, stat in agg.columns]
    agg = agg.reset_index()

    # Merge with GT
    dataset = gt.merge(agg, on="subject_activity", how="inner")

    X = dataset.drop(columns=["subject_activity", "y_true"])
    y = dataset["y_true"].astype(int)

    return X, y, dataset

gt = pd.read_csv('../labels_v2.csv', sep=';').rename(columns={'subject/task':'subject_activity', 'binary-stress':'y_true'}).drop(['affect3-class', 'affect3-class-v2'], axis=1)
gt

    subject_activity  y_true
0     2ea4_Breathing       0
1     2ea4_Counting1       1
2     2ea4_Counting2       1
3     2ea4_Counting3       1
4          2ea4_Math       1
..               ...     ...
695       y9z6_Relax       0
696    y9z6_Speaking       1
697      y9z6_Stroop       1
698      y9z6_Video1       1
699      y9z6_Video2       0

[700 rows x 2 columns]

In [50]:
X, y, agg_df = task_aggregation(df_features, gt)

In [57]:
X.isna().sum()

rms_mean_mean             0
rms_mean_std             10
rms_mean_max              0
rms_std_mean              0
rms_std_std              10
                         ..
voiced_ratio_std         10
voiced_ratio_max          0
low_energy_ratio_mean     0
low_energy_ratio_std     10
low_energy_ratio_max      0
Length: 108, dtype: int64

In [59]:
nan_cols = agg_df.isna().sum()
nan_cols[nan_cols > 0].sort_values(ascending=False)

rms_mean_std            10
rms_std_std             10
zcr_mean_std            10
zcr_std_std             10
mfcc_1_mean_std         10
mfcc_1_std_std          10
mfcc_2_mean_std         10
mfcc_2_std_std          10
mfcc_3_mean_std         10
mfcc_3_std_std          10
mfcc_4_mean_std         10
mfcc_4_std_std          10
mfcc_5_mean_std         10
mfcc_5_std_std          10
mfcc_6_mean_std         10
mfcc_6_std_std          10
mfcc_7_mean_std         10
mfcc_7_std_std          10
mfcc_8_mean_std         10
mfcc_8_std_std          10
mfcc_9_mean_std         10
mfcc_9_std_std          10
mfcc_10_mean_std        10
mfcc_10_std_std         10
mfcc_11_mean_std        10
mfcc_11_std_std         10
mfcc_12_mean_std        10
mfcc_12_std_std         10
mfcc_13_mean_std        10
mfcc_13_std_std         10
pitch_mean_std          10
pitch_std_std           10
pitch_min_std           10
pitch_max_std           10
voiced_ratio_std        10
low_energy_ratio_std    10
dtype: int64

Estos son los casos en que solo se pudo extraer 1 ventana, por lo que no se pudo computar la desviacion. Podemos imputarlos con 0, refiriendo a que no hay cambios entre ventanas.

In [62]:
std_cols = [c for c in agg_df.columns if c.endswith("_std")]
agg_df[std_cols] = agg_df[std_cols].fillna(0)
X[std_cols] = X[std_cols].fillna(0)
nan_cols = agg_df.isna().sum()
nan_cols[nan_cols > 0].sort_values(ascending=False)

Series([], dtype: int64)

In [ ]:
clf = Pipeline([
    #("imputer", SimpleImputer(strategy="median")),
    ("scaler", StandardScaler()),
    ("model", LogisticRegression(max_iter=1000, class_weight="balanced"))
])

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

scores = cross_validate(
    clf,
    X,
    y,
    cv=cv,
    scoring=["accuracy", "balanced_accuracy", "f1", "precision", "recall"],
)

pd.DataFrame(scores).mean()

fit_time                  0.008908
score_time                0.005690
test_accuracy             0.517960
test_balanced_accuracy    0.476774
test_f1                   0.629096
test_precision            0.701607
test_recall               0.571644
dtype: float64

In [64]:
y.value_counts(normalize=True)

y_true
1    0.717452
0    0.282548
Name: proportion, dtype: float64

# Decision-Level Aggregation

In [20]:
import pandas as pd
import numpy as np
from sklearn.model_selection import StratifiedGroupKFold
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score, balanced_accuracy_score

# 1. Load the datasets (replace with your actual file paths)
features_df = pd.read_csv("./audio_features_5s_0overlap.csv")
gt_df = pd.read_csv("../labels_v2.csv", sep=";") # Note the semicolon separator

# 2. Merge the dataframes
# We use an inner join so we only keep windows that have a corresponding ground truth label
merged_df = pd.merge(
    features_df, 
    gt_df, 
    left_on="subject_activity", 
    right_on="subject/task", 
    how="inner"
)

# 3. Define feature columns and target
# Exclude metadata and labels to isolate the pure audio features
exclude_cols = [
    "subject", "activity", "window_id", "subject_activity", 
    "subject/task", "binary-stress", "affect3-class", "affect3-class-v2"
]
feature_cols = [col for col in merged_df.columns if col not in exclude_cols]

X = merged_df[feature_cols]
y = merged_df["binary-stress"]
groups = merged_df["subject_activity"] # Crucial for preventing data leakage

In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import StratifiedGroupKFold
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, balanced_accuracy_score

# [Assume X, y, and groups are already defined from the previous merging step]

# ---------------------------------------------------------
# 1. Stratified Group Splitting
# ---------------------------------------------------------
# StratifiedGroupKFold ensures that the ratio of stress/relaxed tasks is maintained
# in both train and test sets, while preventing data leakage across windows.
sgkf = StratifiedGroupKFold(n_splits=5, shuffle=True, random_state=42)

# We use `next()` to grab just the first split for a standard train/test evaluation.
# (If you want to do full cross-validation, you would loop over sgkf.split instead).
train_idx, test_idx = next(sgkf.split(X, y, groups))

X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]
y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]
groups_test = groups.iloc[test_idx]


# ---------------------------------------------------------
# 2. Window-Level Training with Class Penalization
# ---------------------------------------------------------
# class_weight="balanced" automatically calculates weights inversely proportional 
# to class frequencies in the input data, heavily penalizing mistakes on Class 0.
clf = RandomForestClassifier(
    n_estimators=100, 
    random_state=123, 
    n_jobs=-1, 
    class_weight="balanced"  # <-- The key change to handle the 4:1 imbalance
)

clf.fit(X_train, y_train)

# Predict probabilities on the test set
window_pred_probs = clf.predict_proba(X_test)[:, 1]


# ---------------------------------------------------------
# 3. Decision-Level Aggregation
# ---------------------------------------------------------
test_results_df = pd.DataFrame({
    "subject_activity": groups_test,
    "true_label": y_test,
    "pred_prob": window_pred_probs
})

# Aggregate probabilities by task
task_results = test_results_df.groupby("subject_activity").agg(
    true_label=("true_label", "first"),
    mean_prob=("pred_prob", "mean")
).reset_index()

# Apply the threshold to get binary predictions
task_results["pred_label"] = (task_results["mean_prob"] >= 0.5).astype(int)


# ---------------------------------------------------------
# 4. Final Evaluation
# ---------------------------------------------------------
print("Task-Level Evaluation (Balanced & Stratified):")
print("-" * 50)
print(classification_report(task_results["true_label"], task_results["pred_label"]))

# Using scikit-learn's built-in balanced accuracy metric
b_acc = balanced_accuracy_score(task_results["true_label"], task_results["pred_label"])
print(f"Task-Level Balanced Accuracy: {b_acc:.4f}")

Task-Level Evaluation (Balanced & Stratified):
--------------------------------------------------
              precision    recall  f1-score   support

           0       0.75      0.14      0.24        21
           1       0.74      0.98      0.84        52

    accuracy                           0.74        73
   macro avg       0.74      0.56      0.54        73
weighted avg       0.74      0.74      0.67        73

Task-Level Balanced Accuracy: 0.5618

## Undersampling

In [39]:
from imblearn.under_sampling import RandomUnderSampler

# Initialize the undersampler
rus = RandomUnderSampler(random_state=123)

# Undersample the training data
# Note: We don't need to pass groups here because the train/test split 
# (which already prevented group leakage) has already happened.
X_train_resampled, y_train_resampled = rus.fit_resample(X_train, y_train)

# Train the model on the perfectly balanced training data
clf = RandomForestClassifier(n_estimators=100, random_state=123, n_jobs=-1)
clf.fit(X_train_resampled, y_train_resampled)

window_pred_probs = clf.predict_proba(X_test)[:, 1]


# ---------------------------------------------------------
# 3. Decision-Level Aggregation
# ---------------------------------------------------------
test_results_df = pd.DataFrame({
    "subject_activity": groups_test,
    "true_label": y_test,
    "pred_prob": window_pred_probs
})

# Aggregate probabilities by task
task_results = test_results_df.groupby("subject_activity").agg(
    true_label=("true_label", "first"),
    mean_prob=("pred_prob", "mean")
).reset_index()

# Apply the threshold to get binary predictions
task_results["pred_label"] = (task_results["mean_prob"] >= 0.5).astype(int)


# ---------------------------------------------------------
# 4. Final Evaluation
# ---------------------------------------------------------
print("Task-Level Evaluation (Balanced & Stratified):")
print("-" * 50)
print(classification_report(task_results["true_label"], task_results["pred_label"]))

# Using scikit-learn's built-in balanced accuracy metric
b_acc = balanced_accuracy_score(task_results["true_label"], task_results["pred_label"])
print(f"Task-Level Balanced Accuracy: {b_acc:.4f}")

Task-Level Evaluation (Balanced & Stratified):
--------------------------------------------------
              precision    recall  f1-score   support

           0       0.43      0.48      0.45        21
           1       0.78      0.75      0.76        52

    accuracy                           0.67        73
   macro avg       0.61      0.61      0.61        73
weighted avg       0.68      0.67      0.68        73

Task-Level Balanced Accuracy: 0.6131

In [50]:
merged_df[merged_df['binary-stress'] == 0]['activity'].value_counts()

activity
Reading      238
Counting3    134
Counting1    130
Speaking     128
Math         110
Counting2     92
Stroop        61
Name: count, dtype: int64

In [52]:
# Import the balanced classifier
from imblearn.ensemble import BalancedRandomForestClassifier

# ---------------------------------------------------------
# 1. Stratified Group Splitting
# ---------------------------------------------------------
# StratifiedGroupKFold ensures that the ratio of stress/relaxed tasks is maintained
# in both train and test sets, while preventing data leakage across windows.
sgkf = StratifiedGroupKFold(n_splits=5, shuffle=True, random_state=42)

# We use `next()` to grab just the first split for a standard train/test evaluation.
# (If you want to do full cross-validation, you would loop over sgkf.split instead).
train_idx, test_idx = next(sgkf.split(X, y, groups))

X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]
y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]
groups_test = groups.iloc[test_idx]

# Replace the scikit-learn RandomForestClassifier with the imblearn one
clf = BalancedRandomForestClassifier(
    n_estimators=100, 
    random_state=123, 
    n_jobs=-1,
    # 'sampling_strategy' dictates the balancing. 'auto' means it will 
    # undersample the majority class to match the minority class perfectly.
    sampling_strategy='auto' 
)

# Train and predict exactly as before
clf.fit(X_train, y_train)
window_pred_probs = clf.predict_proba(X_test)[:, 1]

# ---------------------------------------------------------
# 3. Decision-Level Aggregation
# ---------------------------------------------------------
test_results_df = pd.DataFrame({
    "subject_activity": groups_test,
    "true_label": y_test,
    "pred_prob": window_pred_probs
})

# Aggregate probabilities by task
task_results = test_results_df.groupby("subject_activity").agg(
    true_label=("true_label", "first"),
    mean_prob=("pred_prob", "mean")
).reset_index()

# Apply the threshold to get binary predictions
task_results["pred_label"] = (task_results["mean_prob"] >= 0.5).astype(int)


# ---------------------------------------------------------
# 4. Final Evaluation
# ---------------------------------------------------------
print("Task-Level Evaluation (Balanced & Stratified):")
print("-" * 50)
print(classification_report(task_results["true_label"], task_results["pred_label"]))

# Using scikit-learn's built-in balanced accuracy metric
b_acc = balanced_accuracy_score(task_results["true_label"], task_results["pred_label"])
print(f"Task-Level Balanced Accuracy: {b_acc:.4f}")

Task-Level Evaluation (Balanced & Stratified):
--------------------------------------------------
              precision    recall  f1-score   support

           0       0.34      0.52      0.42        21
           1       0.76      0.60      0.67        52

    accuracy                           0.58        73
   macro avg       0.55      0.56      0.54        73
weighted avg       0.64      0.58      0.59        73

Task-Level Balanced Accuracy: 0.5600

## Agregation methods tuning

In [54]:
import pandas as pd
import numpy as np
from sklearn.metrics import balanced_accuracy_score, recall_score
from sklearn.model_selection import StratifiedGroupKFold, cross_val_predict

# Define the aggregation strategies
agg_strategies = {
    "Mean": "mean",
    "Median": "median",
    "Max": "max",
    "75th_Percentile": lambda x: np.percentile(x, 75)
}

results_list = []

# ---------------------------------------------------------------------
# 1. THE FIX: Generate UNBIASED probabilities for the training set
# We use a 3-fold CV internally on the training data to get realistic probabilities
# ---------------------------------------------------------------------
cv_train = StratifiedGroupKFold(n_splits=3, shuffle=True, random_state=42)

# cross_val_predict handles the splitting, training, and predicting automatically
train_unbiased_probs = cross_val_predict(
    clf, X_train, y_train, 
    groups=groups.iloc[train_idx], 
    cv=cv_train, 
    method='predict_proba',
    n_jobs=-1
)[:, 1]

# Rebuild train_base_df using these unbiased probabilities and .values to align indices
train_base_df = pd.DataFrame({
    "subject_activity": groups.iloc[train_idx].values,
    "true_label": y_train.values,
    "pred_prob": train_unbiased_probs 
})

# Test probabilities remain the same (from your trained 'clf' model)
test_base_df = pd.DataFrame({
    "subject_activity": groups_test.values,
    "true_label": y_test.values,
    "pred_prob": window_pred_probs 
})

# ---------------------------------------------------------------------
# 2. Strategy Loop
# ---------------------------------------------------------------------
for strategy_name, agg_func in agg_strategies.items():
    
    # --- A. Aggregate Training Data ---
    train_agg = train_base_df.groupby("subject_activity").agg(
        true_label=("true_label", "first"),
        agg_prob=("pred_prob", agg_func)
    ).reset_index()
    
    # --- B. Find Optimal Threshold on UNBIASED Training Data ---
    best_thresh = 0.5
    best_b_acc = 0
    
    for thresh in np.arange(0.1, 0.9, 0.02):
        train_preds = (train_agg["agg_prob"] >= thresh).astype(int)
        b_acc = balanced_accuracy_score(train_agg["true_label"], train_preds)
        
        # Using >= instead of > so it drifts closer to 0.5 if multiple thresholds tie
        if b_acc >= best_b_acc: 
            best_b_acc = b_acc
            best_thresh = thresh
            
    # --- C. Aggregate Test Data ---
    test_agg = test_base_df.groupby("subject_activity").agg(
        true_label=("true_label", "first"),
        agg_prob=("pred_prob", agg_func)
    ).reset_index()
    
    # --- D. Apply the Optimal Threshold to Test Data ---
    test_preds = (test_agg["agg_prob"] >= best_thresh).astype(int)
    
    # --- E. Calculate Metrics ---
    final_b_acc = balanced_accuracy_score(test_agg["true_label"], test_preds)
    recall_0 = recall_score(test_agg["true_label"], test_preds, pos_label=0, zero_division=0)
    recall_1 = recall_score(test_agg["true_label"], test_preds, pos_label=1, zero_division=0)
    
    results_list.append({
        "Strategy": strategy_name,
        "Optimal_Thresh": round(best_thresh, 2),
        "Balanced_Acc": round(final_b_acc, 4),
        "Recall_Relaxed": round(recall_0, 2),
        "Recall_Stress": round(recall_1, 2)
    })

# 3. Display the final comparison table
comparison_df = pd.DataFrame(results_list)
print("\n=== Aggregation Strategy Comparison ===")
print(comparison_df.to_string(index=False))

=== Aggregation Strategy Comparison ===
       Strategy  Optimal_Thresh  Balanced_Acc  Recall_Relaxed  Recall_Stress
           Mean            0.52        0.5453            0.57           0.52
         Median            0.48        0.5650            0.48           0.65
            Max            0.74        0.5444            0.76           0.33
75th_Percentile            0.56        0.5266            0.48           0.58

In [ ]:

# 1. Define Models
# # Note: XGBoost uses 'scale_pos_weight' for imbalance. Since Class 1 (Stress) 
# is your majority class, we calculate the ratio of Class 0 to Class 1.
scale_weight = (y_train == 0).sum() / (y_train == 1).sum()

models = {
    "Logistic Regression": make_pipeline(
        StandardScaler(), 
        LogisticRegression(class_weight='balanced', max_iter=2000, random_state=42)
    ),
    "Balanced Random Forest": make_pipeline(
        StandardScaler(), # Not strictly necessary for RF, but keeps the pipeline uniform
        BalancedRandomForestClassifier(n_estimators=100, sampling_strategy='auto', random_state=42, n_jobs=-1)
    ),
    "XGBoost": make_pipeline(
        StandardScaler(),
        XGBClassifier(scale_pos_weight=scale_weight, eval_metric='logloss', random_state=42, n_jobs=-1)
    )
}

# 2. Define Aggregation Strategies
agg_strategies = {
    "Mean": "mean",
    "Median": "median",
    "Max": "max",
    "75th_Percentile": lambda x: np.percentile(x, 75)
}

cv_train = StratifiedGroupKFold(n_splits=3, shuffle=True, random_state=42)
results_list = []

print("Running models and generating out-of-fold predictions. This may take a moment...\n")

# 3. Master Loop
for model_name, model in models.items():
    
    # --- A. Train and get unbiased probabilities ---
    # Fit the model on the full training set for the final test set prediction
    model.fit(X_train, y_train)
    test_probs = model.predict_proba(X_test)[:, 1]
    
    # Get out-of-fold probabilities for threshold tuning
    train_unbiased_probs = cross_val_predict(
        model, X_train, y_train, 
        groups=groups.iloc[train_idx], 
        cv=cv_train, 
        method='predict_proba',
        n_jobs=-1
    )[:, 1]
    
    train_base_df = pd.DataFrame({
        "subject_activity": groups.iloc[train_idx].values,
        "true_label": y_train.values,
        "pred_prob": train_unbiased_probs 
    })
    
    test_base_df = pd.DataFrame({
        "subject_activity": groups_test.values,
        "true_label": y_test.values,
        "pred_prob": test_probs 
    })

    # --- B. Test Aggregation Strategies ---
    for strategy_name, agg_func in agg_strategies.items():
        
        train_agg = train_base_df.groupby("subject_activity").agg(
            true_label=("true_label", "first"),
            agg_prob=("pred_prob", agg_func)
        ).reset_index()
        
        # Tune Threshold
        best_thresh = 0.5
        best_b_acc = 0
        for thresh in np.arange(0.1, 0.9, 0.02):
            train_preds = (train_agg["agg_prob"] >= thresh).astype(int)
            b_acc = balanced_accuracy_score(train_agg["true_label"], train_preds)
            if b_acc >= best_b_acc: 
                best_b_acc = b_acc
                best_thresh = thresh
                
        test_agg = test_base_df.groupby("subject_activity").agg(
            true_label=("true_label", "first"),
            agg_prob=("pred_prob", agg_func)
        ).reset_index()
        
        # Apply Threshold and Evaluate
        test_preds = (test_agg["agg_prob"] >= best_thresh).astype(int)
        final_b_acc = balanced_accuracy_score(test_agg["true_label"], test_preds)
        recall_0 = recall_score(test_agg["true_label"], test_preds, pos_label=0, zero_division=0)
        recall_1 = recall_score(test_agg["true_label"], test_preds, pos_label=1, zero_division=0)
        
        results_list.append({
            "Model": model_name,
            "Strategy": strategy_name,
            "Thresh": round(best_thresh, 2),
            "Bal_Acc": round(final_b_acc, 4),
            "Rec_Relaxed": round(recall_0, 2),
            "Rec_Stress": round(recall_1, 2)
        })

# 4. Display Results (Sorted by Balanced Accuracy)
comparison_df = pd.DataFrame(results_list)
comparison_df = comparison_df.sort_values(by="Bal_Acc", ascending=False).reset_index(drop=True)

print("=== Final Classical ML Benchmark Comparison ===")
print(comparison_df.to_string(index=False))

Running models and generating out-of-fold predictions. This may take a moment...

=== Final Classical ML Benchmark Comparison ===
                 Model        Strategy  Thresh  Bal_Acc  Rec_Relaxed  Rec_Stress
               XGBoost 75th_Percentile    0.86   0.6181         0.43        0.81
               XGBoost            Mean    0.56   0.6090         0.33        0.88
               XGBoost          Median    0.60   0.6090         0.33        0.88
               XGBoost             Max    0.88   0.5710         0.24        0.90
Balanced Random Forest            Mean    0.38   0.5664         0.19        0.94
   Logistic Regression          Median    0.60   0.5591         0.71        0.40
Balanced Random Forest             Max    0.72   0.5449         0.67        0.42
Balanced Random Forest          Median    0.60   0.5444         0.76        0.33
Balanced Random Forest 75th_Percentile    0.62   0.5398         0.71        0.37
   Logistic Regression 75th_Percentile    0.62   0.5261         0.57        0.48
   Logistic Regression             Max    0.80   0.5252         0.76        0.29
   Logistic Regression            Mean    0.56   0.5165         0.57        0.46

# Audio Embeddings

## Wav2Vec 2.0:

In [6]:
import os
import pandas as pd
import numpy as np
import torch
import torchaudio
from transformers import Wav2Vec2Processor, Wav2Vec2Model
from tqdm import tqdm
from huggingface_hub import login

# 1. Setup paths (Update these to your actual paths)
AUDIO_WINDOWS_DIR = "./data/5s_0overlap" # The output_dir from your function
GROUND_TRUTH_CSV = "../labels_v2.csv" # Your task-level GT file

# 2. Setup Device and Load Model
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

login('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')
model_name = "facebook/wav2vec2-base"
processor = Wav2Vec2Processor.from_pretrained(model_name)
model = Wav2Vec2Model.from_pretrained(model_name).to(device)
model.eval() # Freeze the model

target_sample_rate = 16000
embedding_list = []

print("Crawling directories and extracting Wav2Vec 2.0 embeddings...")

# 3. Extraction Loop based on your directory structure
with torch.no_grad():
    for subject in tqdm(sorted(os.listdir(AUDIO_WINDOWS_DIR)), desc="Subjects"):
        subject_dir = os.path.join(AUDIO_WINDOWS_DIR, subject)
        if not os.path.isdir(subject_dir): continue
            
        for activity in sorted(os.listdir(subject_dir)):
            activity_dir = os.path.join(subject_dir, activity)
            if not os.path.isdir(activity_dir): continue
                
            # Reconstruct the ID to match your ground truth (e.g., "2ea4_Counting1")
            subject_activity = f"{subject}_{activity}"
            
            for window_file in sorted(os.listdir(activity_dir)):
                if not window_file.lower().endswith(".wav"): continue
                    
                # Extract window_id from filename (e.g., "window_0.wav" -> 0)
                window_id = int(window_file.split("_")[1].split(".")[0])
                file_path = os.path.join(activity_dir, window_file)
                
                # A. Load audio
                waveform, sample_rate = torchaudio.load(file_path)
                if waveform.shape[0] > 1:
                    waveform = torch.mean(waveform, dim=0, keepdim=True)
                    
                # Safety check, though your function should have saved it at 16kHz
                if sample_rate != target_sample_rate:
                    resampler = torchaudio.transforms.Resample(orig_freq=sample_rate, new_freq=target_sample_rate)
                    waveform = resampler(waveform)
                    
                # B. Process and Forward Pass
                inputs = processor(waveform.squeeze().numpy(), sampling_rate=target_sample_rate, return_tensors="pt")
                inputs = {key: val.to(device) for key, val in inputs.items()}
                outputs = model(**inputs)
                
                # C. Temporal Pooling (Mean across sequence length)
                mean_pooled_embedding = outputs.last_hidden_state.mean(dim=1).squeeze().cpu().numpy()
                
                # D. Store results
                row_data = {
                    "subject": subject,
                    "activity": activity,
                    "subject_activity": subject_activity,
                    "window_id": window_id
                }
                
                for i, val in enumerate(mean_pooled_embedding):
                    row_data[f"w2v_{i}"] = val
                    
                embedding_list.append(row_data)

# 4. Create DataFrame and Merge with Ground Truth
embeddings_df = pd.DataFrame(embedding_list)

print("Merging with ground truth labels...")
gt_df = pd.read_csv(GROUND_TRUTH_CSV, sep=";")

# Merge using your established mapping
merged_df = pd.merge(
    embeddings_df, 
    gt_df, 
    left_on="subject_activity", 
    right_on="subject/task", 
    how="inner"
)

merged_df.to_csv("wav2vec_embeddings.csv", index=False)
print(f"Extraction complete! Saved {len(merged_df)} windows to {output_csv}.")

Using device: cpu

Loading weights: 100%|██████████| 211/211 [00:00<00:00, 60101.74it/s]
[transformers] Wav2Vec2Model LOAD REPORT from: facebook/wav2vec2-base
Key                          | Status     |  |
-----------------------------+------------+--+-
project_hid.weight           | UNEXPECTED |  |
project_q.bias               | UNEXPECTED |  |
project_q.weight             | UNEXPECTED |  |
quantizer.weight_proj.weight | UNEXPECTED |  |
quantizer.weight_proj.bias   | UNEXPECTED |  |
quantizer.codevectors        | UNEXPECTED |  |
project_hid.bias             | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Crawling directories and extracting Wav2Vec 2.0 embeddings...

Subjects: 100%|██████████| 54/54 [09:46<00:00, 10.86s/it]

Merging with ground truth labels...
Extraction complete! Saved 0 windows to wav2vec_embeddings.csv.

In [10]:
embeddings_df['activity'] = embeddings_df['activity'].apply(lambda x: x.split('_')[1])
embeddings_df['subject_activity'] = embeddings_df['subject_activity'].apply(lambda x: "_".join(x.split('_')[1:3]))

In [11]:
merged_df = pd.merge(
    embeddings_df, 
    gt_df, 
    left_on="subject_activity", 
    right_on="subject/task", 
    how="inner"
)

In [13]:
merged_df.to_csv("wav2vec_embeddings.csv", index=False)

In [ ]:
import warnings

# Suppress minor warnings for clean output
warnings.filterwarnings("ignore")

# 1. Load the new Wav2Vec 2.0 Dataset
print("Loading Wav2Vec 2.0 embeddings...")
df = pd.read_csv("wav2vec_embeddings.csv")

# Extract features, target, and groups
# .filter(regex='^w2v_') neatly grabs only the 768 embedding columns
X = df.filter(regex='^w2v_')
y = df["binary-stress"]
groups = df["subject_activity"]

# 2. Setup the exact same split as before
sgkf = StratifiedGroupKFold(n_splits=5, shuffle=True, random_state=42)
train_idx, test_idx = next(sgkf.split(X, y, groups))

X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]
y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]

# Calculate imbalance weight for XGBoost
scale_weight = (y_train == 0).sum() / (y_train == 1).sum()

# 3. Define Models (Same as classical baseline)
models = {
    "Logistic Regression": make_pipeline(
        StandardScaler(), 
        LogisticRegression(class_weight='balanced', max_iter=2000, random_state=42)
    ),
    "Balanced Random Forest": make_pipeline(
        StandardScaler(),
        BalancedRandomForestClassifier(n_estimators=100, sampling_strategy='auto', random_state=42, n_jobs=-1)
    ),
    "XGBoost": make_pipeline(
        StandardScaler(),
        XGBClassifier(scale_pos_weight=scale_weight, eval_metric='logloss', random_state=42, n_jobs=-1)
    )
}

agg_strategies = {
    "Mean": "mean",
    "Median": "median",
    "Max": "max",
    "75th_Percentile": lambda x: np.percentile(x, 75)
}

cv_train = StratifiedGroupKFold(n_splits=3, shuffle=True, random_state=42)
results_list = []

print("Running models and generating out-of-fold predictions. This may take a few minutes...")

# 4. Master Loop
for model_name, model in models.items():
    
    # Train and predict
    model.fit(X_train, y_train)
    test_probs = model.predict_proba(X_test)[:, 1]
    
    # Out-of-fold probabilities for unbiased threshold tuning
    train_unbiased_probs = cross_val_predict(
        model, X_train, y_train, 
        groups=groups.iloc[train_idx], 
        cv=cv_train, 
        method='predict_proba',
        n_jobs=-1
    )[:, 1]
    
    train_base_df = pd.DataFrame({
        "subject_activity": groups.iloc[train_idx].values,
        "true_label": y_train.values,
        "pred_prob": train_unbiased_probs 
    })
    
    test_base_df = pd.DataFrame({
        "subject_activity": groups.iloc[test_idx].values,
        "true_label": y_test.values,
        "pred_prob": test_probs 
    })

    # Test Aggregation Strategies
    for strategy_name, agg_func in agg_strategies.items():
        
        train_agg = train_base_df.groupby("subject_activity").agg(
            true_label=("true_label", "first"),
            agg_prob=("pred_prob", agg_func)
        ).reset_index()
        
        best_thresh = 0.5
        best_b_acc = 0
        for thresh in np.arange(0.1, 0.9, 0.02):
            train_preds = (train_agg["agg_prob"] >= thresh).astype(int)
            b_acc = balanced_accuracy_score(train_agg["true_label"], train_preds)
            if b_acc >= best_b_acc: 
                best_b_acc = b_acc
                best_thresh = thresh
                
        test_agg = test_base_df.groupby("subject_activity").agg(
            true_label=("true_label", "first"),
            agg_prob=("pred_prob", agg_func)
        ).reset_index()
        
        test_preds = (test_agg["agg_prob"] >= best_thresh).astype(int)
        final_b_acc = balanced_accuracy_score(test_agg["true_label"], test_preds)
        recall_0 = recall_score(test_agg["true_label"], test_preds, pos_label=0, zero_division=0)
        recall_1 = recall_score(test_agg["true_label"], test_preds, pos_label=1, zero_division=0)
        
        results_list.append({
            "Model": model_name,
            "Strategy": strategy_name,
            "Thresh": round(best_thresh, 2),
            "Bal_Acc": round(final_b_acc, 4),
            "Rec_Relaxed": round(recall_0, 2),
            "Rec_Stress": round(recall_1, 2)
        })

comparison_df = pd.DataFrame(results_list)
comparison_df = comparison_df.sort_values(by="Bal_Acc", ascending=False).reset_index(drop=True)

print("\n=== Final Deep Audio (Wav2Vec 2.0) Benchmark Comparison ===")
print(comparison_df.to_string(index=False))

Loading Wav2Vec 2.0 embeddings...
Running models and generating out-of-fold predictions. This may take a few minutes...

=== Final Deep Audio (Wav2Vec 2.0) Benchmark Comparison ===
                 Model        Strategy  Thresh  Bal_Acc  Rec_Relaxed  Rec_Stress
   Logistic Regression          Median    0.56   0.6277         0.43        0.83
               XGBoost            Mean    0.70   0.6277         0.43        0.83
Balanced Random Forest             Max    0.68   0.6071         0.71        0.50
   Logistic Regression            Mean    0.60   0.5989         0.43        0.77
   Logistic Regression 75th_Percentile    0.76   0.5897         0.33        0.85
   Logistic Regression             Max    0.88   0.5856         0.19        0.98
               XGBoost 75th_Percentile    0.86   0.5852         0.29        0.88
Balanced Random Forest            Mean    0.38   0.5760         0.19        0.96
Balanced Random Forest 75th_Percentile    0.58   0.5737         0.67        0.48
Balanced Random Forest          Median    0.44   0.5705         0.33        0.81
               XGBoost          Median    0.76   0.5563         0.29        0.83
               XGBoost             Max    0.88   0.5522         0.14        0.96

## HuBert

In [25]:
from transformers import Wav2Vec2FeatureExtractor, HubertModel
from tqdm import tqdm

# 1. Setup paths (Update these to your actual paths)
AUDIO_WINDOWS_DIR = "./data/5s_0overlap" 
GROUND_TRUTH_CSV = "../labels_v2.csv"

# 2. Setup Device and Load Model
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

model_name = "facebook/hubert-base-ls960"
# HuBERT uses the same feature extractor logic as Wav2Vec2 for raw audio
processor = Wav2Vec2FeatureExtractor.from_pretrained(model_name)
model = HubertModel.from_pretrained(model_name).to(device)
model.eval() # Freeze the model

target_sample_rate = 16000
embedding_list = []

print("Extracting HuBERT embeddings...")

# 3. Extraction Loop
with torch.no_grad():
    for subject in tqdm(sorted(os.listdir(AUDIO_WINDOWS_DIR)), desc="Subjects"):
        subject_dir = os.path.join(AUDIO_WINDOWS_DIR, subject)
        if not os.path.isdir(subject_dir): continue
            
        for subject_activity in sorted(os.listdir(subject_dir)):
            activity_dir = os.path.join(subject_dir, subject_activity)
            if not os.path.isdir(activity_dir): continue
                
            # Using the fix we established earlier
            activity = subject_activity.split('_')[1]
            
            for window_file in sorted(os.listdir(activity_dir)):
                if not window_file.lower().endswith(".wav"): continue
                    
                window_id = int(window_file.split("_")[1].split(".")[0])
                file_path = os.path.join(activity_dir, window_file)
                
                # Load audio
                waveform, sample_rate = torchaudio.load(file_path)
                if waveform.shape[0] > 1:
                    waveform = torch.mean(waveform, dim=0, keepdim=True)
                    
                if sample_rate != target_sample_rate:
                    resampler = torchaudio.transforms.Resample(orig_freq=sample_rate, new_freq=target_sample_rate)
                    waveform = resampler(waveform)
                    
                # Process and Forward Pass
                inputs = processor(waveform.squeeze().numpy(), sampling_rate=target_sample_rate, return_tensors="pt")
                inputs = {key: val.to(device) for key, val in inputs.items()}
                outputs = model(**inputs)
                
                # Temporal Pooling
                mean_pooled_embedding = outputs.last_hidden_state.mean(dim=1).squeeze().cpu().numpy()
                
                # Store results
                row_data = {
                    "subject": subject,
                    "activity": activity,
                    "subject_activity": subject_activity,
                    "window_id": window_id
                }
                
                # Use 'hubert_' prefix just to keep things clean
                for i, val in enumerate(mean_pooled_embedding):
                    row_data[f"hubert_{i}"] = val
                    
                embedding_list.append(row_data)

# 4. Create DataFrame and Merge with Ground Truth
embeddings_df = pd.DataFrame(embedding_list)

print("Merging with ground truth labels...")
gt_df = pd.read_csv(GROUND_TRUTH_CSV, sep=";")

merged_df = pd.merge(
    embeddings_df, 
    gt_df, 
    left_on="subject_activity", 
    right_on="subject/task", 
    how="inner"
)

output_csv = "hubert_embeddings.csv"
merged_df.to_csv(output_csv, index=False)
print(f"Extraction complete! Saved {len(merged_df)} windows to {output_csv}.")

Using device: cpu

Loading weights: 100%|██████████| 211/211 [00:00<00:00, 47230.13it/s]

Extracting HuBERT embeddings...

Subjects: 100%|██████████| 54/54 [09:46<00:00, 10.86s/it]

Merging with ground truth labels...
Extraction complete! Saved 3091 windows to hubert_embeddings.csv.

In [27]:
import warnings

# Suppress minor warnings for clean output
warnings.filterwarnings("ignore")

# 1. Load the new Wav2Vec 2.0 Dataset
print("Loading hubert embeddings...")
df = pd.read_csv("hubert_embeddings.csv")

# Extract features, target, and groups
# .filter(regex='^w2v_') neatly grabs only the 768 embedding columns
X = df.filter(regex='^hubert_')
y = df["binary-stress"]
groups = df["subject_activity"]

# 2. Setup the exact same split as before
sgkf = StratifiedGroupKFold(n_splits=5, shuffle=True, random_state=42)
train_idx, test_idx = next(sgkf.split(X, y, groups))

X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]
y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]

# Calculate imbalance weight for XGBoost
scale_weight = (y_train == 0).sum() / (y_train == 1).sum()

# 3. Define Models (Same as classical baseline)
models = {
    "Logistic Regression": make_pipeline(
        StandardScaler(), 
        LogisticRegression(class_weight='balanced', max_iter=2000, random_state=42)
    ),
    "Balanced Random Forest": make_pipeline(
        StandardScaler(),
        BalancedRandomForestClassifier(n_estimators=100, sampling_strategy='auto', random_state=42, n_jobs=-1)
    ),
    "XGBoost": make_pipeline(
        StandardScaler(),
        XGBClassifier(scale_pos_weight=scale_weight, eval_metric='logloss', random_state=42, n_jobs=-1)
    )
}

agg_strategies = {
    "Mean": "mean",
    "Median": "median",
    "Max": "max",
    "75th_Percentile": lambda x: np.percentile(x, 75)
}

cv_train = StratifiedGroupKFold(n_splits=3, shuffle=True, random_state=42)
results_list = []

print("Running models and generating out-of-fold predictions. This may take a few minutes...")

# 4. Master Loop
for model_name, model in models.items():
    
    # Train and predict
    model.fit(X_train, y_train)
    test_probs = model.predict_proba(X_test)[:, 1]
    
    # Out-of-fold probabilities for unbiased threshold tuning
    train_unbiased_probs = cross_val_predict(
        model, X_train, y_train, 
        groups=groups.iloc[train_idx], 
        cv=cv_train, 
        method='predict_proba',
        n_jobs=-1
    )[:, 1]
    
    train_base_df = pd.DataFrame({
        "subject_activity": groups.iloc[train_idx].values,
        "true_label": y_train.values,
        "pred_prob": train_unbiased_probs 
    })
    
    test_base_df = pd.DataFrame({
        "subject_activity": groups.iloc[test_idx].values,
        "true_label": y_test.values,
        "pred_prob": test_probs 
    })

    # Test Aggregation Strategies
    for strategy_name, agg_func in agg_strategies.items():
        
        train_agg = train_base_df.groupby("subject_activity").agg(
            true_label=("true_label", "first"),
            agg_prob=("pred_prob", agg_func)
        ).reset_index()
        
        best_thresh = 0.5
        best_b_acc = 0
        for thresh in np.arange(0.1, 0.9, 0.02):
            train_preds = (train_agg["agg_prob"] >= thresh).astype(int)
            b_acc = balanced_accuracy_score(train_agg["true_label"], train_preds)
            if b_acc >= best_b_acc: 
                best_b_acc = b_acc
                best_thresh = thresh
                
        test_agg = test_base_df.groupby("subject_activity").agg(
            true_label=("true_label", "first"),
            agg_prob=("pred_prob", agg_func)
        ).reset_index()
        
        test_preds = (test_agg["agg_prob"] >= best_thresh).astype(int)
        final_b_acc = balanced_accuracy_score(test_agg["true_label"], test_preds)
        recall_0 = recall_score(test_agg["true_label"], test_preds, pos_label=0, zero_division=0)
        recall_1 = recall_score(test_agg["true_label"], test_preds, pos_label=1, zero_division=0)
        
        results_list.append({
            "Model": model_name,
            "Strategy": strategy_name,
            "Thresh": round(best_thresh, 2),
            "Bal_Acc": round(final_b_acc, 4),
            "Rec_Relaxed": round(recall_0, 2),
            "Rec_Stress": round(recall_1, 2)
        })

comparison_df = pd.DataFrame(results_list)
comparison_df = comparison_df.sort_values(by="Bal_Acc", ascending=False).reset_index(drop=True)

print("\n=== Final Deep Audio (Hubert) Benchmark Comparison ===")
print(comparison_df.to_string(index=False))

Loading hubert embeddings...
Running models and generating out-of-fold predictions. This may take a few minutes...

=== Final Deep Audio (Hubert) Benchmark Comparison ===
                 Model        Strategy  Thresh  Bal_Acc  Rec_Relaxed  Rec_Stress
Balanced Random Forest 75th_Percentile    0.48   0.6516         0.48        0.83
Balanced Random Forest          Median    0.44   0.6277         0.43        0.83
   Logistic Regression 75th_Percentile    0.86   0.6227         0.48        0.77
Balanced Random Forest             Max    0.56   0.6085         0.43        0.79
   Logistic Regression            Mean    0.64   0.6076         0.62        0.60
Balanced Random Forest            Mean    0.40   0.5902         0.24        0.94
   Logistic Regression          Median    0.86   0.5737         0.67        0.48
               XGBoost             Max    0.88   0.5618         0.14        0.98
   Logistic Regression             Max    0.74   0.5426         0.14        0.94
               XGBoost 75th_Percentile    0.86   0.5229         0.24        0.81
               XGBoost            Mean    0.62   0.5087         0.19        0.83
               XGBoost          Median    0.86   0.5078         0.38        0.63

## AST

Vision Transformer applied on audio, which is turned into a spectrogram (an image).

In [2]:
from transformers import ASTFeatureExtractor, ASTModel
from tqdm import tqdm

AUDIO_WINDOWS_DIR = "./data/5s_0overlap" 
GROUND_TRUTH_CSV = "../labels_v2.csv"

# 2. Setup Device and Load Model
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

# We use the standard AST model fine-tuned on AudioSet
login('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')

model_name = "MIT/ast-finetuned-audioset-10-10-0.4593"
processor = ASTFeatureExtractor.from_pretrained(model_name)
model = ASTModel.from_pretrained(model_name).to(device)
model.eval() # Freeze the model

target_sample_rate = 16000
embedding_list = []

print("Extracting AST embeddings...")

# 3. Extraction Loop
with torch.no_grad():
    for subject in tqdm(sorted(os.listdir(AUDIO_WINDOWS_DIR)), desc="Subjects"):
        subject_dir = os.path.join(AUDIO_WINDOWS_DIR, subject)
        if not os.path.isdir(subject_dir): continue
            
        for subject_activity in sorted(os.listdir(subject_dir)):
            activity_dir = os.path.join(subject_dir, activity)
            if not os.path.isdir(activity_dir): continue
                
            # Using the established fix for the ID
            activity = subject_activity.split("_")[1]
            
            for window_file in sorted(os.listdir(activity_dir)):
                if not window_file.lower().endswith(".wav"): continue
                    
                window_id = int(window_file.split("_")[1].split(".")[0])
                file_path = os.path.join(activity_dir, window_file)
                
                # Load audio
                waveform, sample_rate = torchaudio.load(file_path)
                if waveform.shape[0] > 1:
                    waveform = torch.mean(waveform, dim=0, keepdim=True)
                    
                if sample_rate != target_sample_rate:
                    resampler = torchaudio.transforms.Resample(orig_freq=sample_rate, new_freq=target_sample_rate)
                    waveform = resampler(waveform)
                    
                # Process and Forward Pass
                # AST expects the raw waveform and handles the spectrogram conversion internally
                inputs = processor(waveform.squeeze().numpy(), sampling_rate=target_sample_rate, return_tensors="pt")
                inputs = {key: val.to(device) for key, val in inputs.items()}
                outputs = model(**inputs)
                
                # Temporal/Patch Pooling
                # AST outputs sequence of patches. We take the mean across the sequence.
                mean_pooled_embedding = outputs.last_hidden_state.mean(dim=1).squeeze().cpu().numpy()
                
                # Store results
                row_data = {
                    "subject": subject,
                    "activity": activity,
                    "subject_activity": subject_activity,
                    "window_id": window_id
                }
                
                # Prefix with 'ast_'
                for i, val in enumerate(mean_pooled_embedding):
                    row_data[f"ast_{i}"] = val
                    
                embedding_list.append(row_data)

# 4. Create DataFrame and Merge with Ground Truth
embeddings_df = pd.DataFrame(embedding_list)

print("Merging with ground truth labels...")
gt_df = pd.read_csv(GROUND_TRUTH_CSV, sep=";")

merged_df = pd.merge(
    embeddings_df, 
    gt_df, 
    left_on="subject_activity", 
    right_on="subject/task", 
    how="inner"
)

output_csv = "ast_embeddings.csv"
merged_df.to_csv(output_csv, index=False)
print(f"Extraction complete! Saved {len(merged_df)} windows to {output_csv}.")

Using device: cpu

Cancellation requested; stopping current tasks.

KeyboardInterrupt:

In [4]:
import warnings

# Suppress minor warnings for clean output
warnings.filterwarnings("ignore")

# 1. Load the new Wav2Vec 2.0 Dataset
print("Loading AST embeddings...")
df = pd.read_csv("ast_embeddings.csv")

# Extract features, target, and groups
# .filter(regex='^w2v_') neatly grabs only the 768 embedding columns
X = df.filter(regex='^ast_')
y = df["binary-stress"]
groups = df["subject_activity"]

# 2. Setup the exact same split as before
sgkf = StratifiedGroupKFold(n_splits=5, shuffle=True, random_state=42)
train_idx, test_idx = next(sgkf.split(X, y, groups))

X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]
y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]

# Calculate imbalance weight for XGBoost
scale_weight = (y_train == 0).sum() / (y_train == 1).sum()

# 3. Define Models (Same as classical baseline)
models = {
    "Logistic Regression": make_pipeline(
        StandardScaler(), 
        LogisticRegression(class_weight='balanced', max_iter=2000, random_state=42)
    ),
    "Balanced Random Forest": make_pipeline(
        StandardScaler(),
        BalancedRandomForestClassifier(n_estimators=100, sampling_strategy='auto', random_state=42, n_jobs=-1)
    ),
    "XGBoost": make_pipeline(
        StandardScaler(),
        XGBClassifier(scale_pos_weight=scale_weight, eval_metric='logloss', random_state=42, n_jobs=-1)
    )
}

agg_strategies = {
    "Mean": "mean",
    "Median": "median",
    "Max": "max",
    "75th_Percentile": lambda x: np.percentile(x, 75)
}

cv_train = StratifiedGroupKFold(n_splits=3, shuffle=True, random_state=42)
results_list = []

print("Running models and generating out-of-fold predictions. This may take a few minutes...")

# 4. Master Loop
for model_name, model in models.items():
    
    # Train and predict
    model.fit(X_train, y_train)
    test_probs = model.predict_proba(X_test)[:, 1]
    
    # Out-of-fold probabilities for unbiased threshold tuning
    train_unbiased_probs = cross_val_predict(
        model, X_train, y_train, 
        groups=groups.iloc[train_idx], 
        cv=cv_train, 
        method='predict_proba',
        n_jobs=-1
    )[:, 1]
    
    train_base_df = pd.DataFrame({
        "subject_activity": groups.iloc[train_idx].values,
        "true_label": y_train.values,
        "pred_prob": train_unbiased_probs 
    })
    
    test_base_df = pd.DataFrame({
        "subject_activity": groups.iloc[test_idx].values,
        "true_label": y_test.values,
        "pred_prob": test_probs 
    })

    # Test Aggregation Strategies
    for strategy_name, agg_func in agg_strategies.items():
        
        train_agg = train_base_df.groupby("subject_activity").agg(
            true_label=("true_label", "first"),
            agg_prob=("pred_prob", agg_func)
        ).reset_index()
        
        best_thresh = 0.5
        best_b_acc = 0
        for thresh in np.arange(0.1, 0.9, 0.02):
            train_preds = (train_agg["agg_prob"] >= thresh).astype(int)
            b_acc = balanced_accuracy_score(train_agg["true_label"], train_preds)
            if b_acc >= best_b_acc: 
                best_b_acc = b_acc
                best_thresh = thresh
                
        test_agg = test_base_df.groupby("subject_activity").agg(
            true_label=("true_label", "first"),
            agg_prob=("pred_prob", agg_func)
        ).reset_index()
        
        test_preds = (test_agg["agg_prob"] >= best_thresh).astype(int)
        final_b_acc = balanced_accuracy_score(test_agg["true_label"], test_preds)
        recall_0 = recall_score(test_agg["true_label"], test_preds, pos_label=0, zero_division=0)
        recall_1 = recall_score(test_agg["true_label"], test_preds, pos_label=1, zero_division=0)
        
        results_list.append({
            "Model": model_name,
            "Strategy": strategy_name,
            "Thresh": round(best_thresh, 2),
            "Bal_Acc": round(final_b_acc, 4),
            "Rec_Relaxed": round(recall_0, 2),
            "Rec_Stress": round(recall_1, 2)
        })

comparison_df = pd.DataFrame(results_list)
comparison_df = comparison_df.sort_values(by="Bal_Acc", ascending=False).reset_index(drop=True)

print("\n=== Final Deep Audio (AST) Benchmark Comparison ===")
print(comparison_df.to_string(index=False))

Loading AST embeddings...
Running models and generating out-of-fold predictions. This may take a few minutes...

=== Final Deep Audio (AST) Benchmark Comparison ===
                 Model        Strategy  Thresh  Bal_Acc  Rec_Relaxed  Rec_Stress
Balanced Random Forest            Mean    0.48   0.6126         0.57        0.65
               XGBoost            Mean    0.80   0.5842         0.48        0.69
               XGBoost          Median    0.86   0.5842         0.48        0.69
               XGBoost 75th_Percentile    0.86   0.5705         0.33        0.81
Balanced Random Forest             Max    0.60   0.5549         0.57        0.54
Balanced Random Forest          Median    0.44   0.5417         0.33        0.75
   Logistic Regression             Max    0.74   0.5380         0.10        0.98
Balanced Random Forest 75th_Percentile    0.52   0.5362         0.48        0.60
               XGBoost             Max    0.66   0.5238         0.05        1.00
   Logistic Regression            Mean    0.72   0.5023         0.52        0.48
   Logistic Regression          Median    0.82   0.4982         0.38        0.62
   Logistic Regression 75th_Percentile    0.88   0.4940         0.24        0.75