# Roadmap

1. Preprocessing con VAD para eliminar ruidos o momentos de silencio.
2. Ventanas con solapamiento.
3. Extracción de características (OpenSMILE, Librosa), según fuentes: Prosody, voice quality, spectral features (MFCC). O modelos como Wav2Vec.
4. Modelización y evaluación.

5. Usar LLMs multimodales para analizar la entrada de audio directamente.

In [ ]:
import torch
import os
import librosa
import soundfile as sf
import numpy as np
import pandas as pd
import torchaudio
from transformers import Wav2Vec2Processor, Wav2Vec2Model
from tqdm import tqdm
from huggingface_hub import login

from sklearn.pipeline import Pipeline, make_pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import StratifiedGroupKFold, cross_val_predict, StratifiedKFold, cross_validate, train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, accuracy_score, balanced_accuracy_score, recall_score, f1_score, precision_score
from xgboost import XGBClassifier
from imblearn.ensemble import BalancedRandomForestClassifier

RANDOM_STATE = 123

# Load and preprocessing

In [2]:
#VAD model
model, utils = torch.hub.load(repo_or_dir='snakers4/silero-vad', model='silero_vad', force_reload=True)
(get_speech_timestamps,save_audio,read_audio,VADIterator,collect_chunks) = utils
sampling_rate = 16000

Downloading: "https://github.com/snakers4/silero-vad/zipball/master" to /home/ethe/.cache/torch/hub/master.zip

In [3]:

def apply_vad(input_dir, output_dir, sampling_rate = 16000, threshold = 0.2, speech_pad_ms=250):

    for subject in os.listdir(input_dir):

        for act in os.listdir(os.path.join(input_dir, subject)):

            audio_path = os.path.join(input_dir, subject, act)
            subject_act = os.path.basename(audio_path).split('.')[0]
            wav = read_audio(audio_path, sampling_rate=sampling_rate)

            speech_timestamps = get_speech_timestamps(wav, 
                                        model, 
                                        sampling_rate=sampling_rate,
                                        threshold = threshold,
                                        speech_pad_ms = speech_pad_ms,
                                        )
            
            if len(speech_timestamps) > 0:
                out_dir = os.path.join(output_dir, subject)
                os.makedirs(out_dir, exist_ok=True)
                save_audio(os.path.join(out_dir, f"{subject_act}.wav"), collect_chunks(speech_timestamps, wav), sampling_rate=sampling_rate)

            else:
                print('VAD failed on', audio_path)

apply_vad(input_dir='./data/original/', output_dir='./data/vad_applied')

/home/ethe/miniconda3/envs/rl_env/lib/python3.11/site-packages/torchaudio/__init__.py:178: UserWarning: The 'bits_per_sample' parameter is not directly supported by TorchCodec AudioEncoder.
  return save_with_torchcodec(

VAD failed on ./data/original/h7j3/h7j3_Counting1.wav
VAD failed on ./data/original/h7j3/h7j3_Counting3.wav
VAD failed on ./data/original/h7j3/h7j3_Math.wav
VAD failed on ./data/original/h7j3/h7j3_Stroop.wav

# Windowing

In [8]:
import os
import numpy as np
import soundfile as sf
import librosa

def save_audio_windows(input_dir, output_dir, window_size=5.0, overlap=0.0, sampling_rate=16000):
    """
    Splits each audio file into fixed-length windows and saves them.

    input_dir structure:
        input_dir/subject/activity.wav

    output_dir structure:
        output_dir/subject/activity/window_0.wav
    """

    stride = window_size * (1 - overlap)

    for subject in sorted(os.listdir(input_dir)):
        subject_dir = os.path.join(input_dir, subject)

        if not os.path.isdir(subject_dir):
            continue

        for act_file in sorted(os.listdir(subject_dir)):
            if not act_file.lower().endswith(".wav"):
                continue

            audio_path = os.path.join(subject_dir, act_file)
            activity = os.path.splitext(act_file)[0]

            y, sr = librosa.load(audio_path, sr=sampling_rate)
            duration = librosa.get_duration(y=y, sr=sr)

            out_act_dir = os.path.join(output_dir, subject, activity)
            os.makedirs(out_act_dir, exist_ok=True)

            start = 0.0
            window_id = 0

            while start + window_size <= duration:
                end = start + window_size

                start_sample = int(start * sr)
                end_sample = int(end * sr)

                y_window = y[start_sample:end_sample]

                out_path = os.path.join(out_act_dir, f"window_{window_id}.wav")
                sf.write(out_path, y_window, sr)

                window_id += 1
                start += stride

            if window_id == 0:
                print(f"No complete windows for: {audio_path}")

        print(f"{subject} done.")

    print("All audio windows saved.")

In [9]:
save_audio_windows(input_dir='./data/vad_applied', output_dir='./data/5s_0overlap')

2ea4 done.
2hpu done.
2z7d done.
45lx done.
4e8r done.
4woj done.
5f7t done.
6g6y done.
6k5f done.
71i5 done.
7h5u done.
7m3c done.
No complete windows for: ./data/vad_applied/8g4y/8g4y_Math.wav
No complete windows for: ./data/vad_applied/8g4y/8g4y_Stroop.wav
8g4y done.
No complete windows for: ./data/vad_applied/8i4i/8i4i_Counting3.wav
No complete windows for: ./data/vad_applied/8i4i/8i4i_Math.wav
No complete windows for: ./data/vad_applied/8i4i/8i4i_Stroop.wav
8i4i done.
9j3o done.
No complete windows for: ./data/vad_applied/9t6n/9t6n_Counting2.wav
9t6n done.
9txq done.
a1k9 done.
b2l8 done.
b9w0 done.
bfl5 done.
c3m7 done.
chdf done.
ctzy done.
cxj0 done.
No complete windows for: ./data/vad_applied/d4n6/d4n6_Stroop.wav
d4n6 done.
e5p4 done.
g7r2 done.
g9j5 done.
No complete windows for: ./data/vad_applied/h7j3/h7j3_Counting2.wav
h7j3 done.
h8r2 done.
h8s1 done.
i9t9 done.
iqyg done.
No complete windows for: ./data/vad_applied/j9h8/j9h8_Counting3.wav
j9h8 done.
k2v7 done.
k67g done.
kkf5 done.
kycf done.
m8g5 done.
p9i3 done.
No complete windows for: ./data/vad_applied/qw5t/qw5t_Counting1.wav
No complete windows for: ./data/vad_applied/qw5t/qw5t_Counting2.wav
No complete windows for: ./data/vad_applied/qw5t/qw5t_Counting3.wav
No complete windows for: ./data/vad_applied/qw5t/qw5t_Stroop.wav
qw5t done.
r3zm done.
r5s8 done.
t6v9 done.
tmvd done.
u3v9 done.
uymz done.
v8mh done.
w2t5 done.
wssm done.
x1q3 done.
y8c3 done.
y9z6 done.
All audio windows saved.

# Paralinguistic audio features extraction using LIBROSA:

In [ ]:
import pandas as pd

def extract_features_from_audio(y, sr):
    features = {}

    # Energy / loudness
    rms = librosa.feature.rms(y=y)[0]
    features["rms_mean"] = np.mean(rms)
    features["rms_std"] = np.std(rms)

    # Zero-crossing rate
    zcr = librosa.feature.zero_crossing_rate(y)[0]
    features["zcr_mean"] = np.mean(zcr)
    features["zcr_std"] = np.std(zcr)

    # MFCCs
    mfcc = librosa.feature.mfcc(y=y, sr=sr, n_mfcc=13)

    for i in range(13):
        features[f"mfcc_{i+1}_mean"] = np.mean(mfcc[i])
        features[f"mfcc_{i+1}_std"] = np.std(mfcc[i])

    # Pitch / F0
    f0, voiced_flag, voiced_probs = librosa.pyin(
        y,
        fmin=librosa.note_to_hz("C2"),
        fmax=librosa.note_to_hz("C7")
    )

    valid_f0 = f0[~np.isnan(f0)]

    if len(valid_f0) > 0:
        features["pitch_mean"] = np.mean(valid_f0)
        features["pitch_std"] = np.std(valid_f0)
        features["pitch_min"] = np.min(valid_f0)
        features["pitch_max"] = np.max(valid_f0)
    else:
        features["pitch_mean"] = 0.0
        features["pitch_std"] = 0.0
        features["pitch_min"] = 0.0
        features["pitch_max"] = 0.0

    # Voiced ratio
    features["voiced_ratio"] = np.mean(voiced_flag) if voiced_flag is not None else 0.0

    # Pause / low-energy ratio
    if len(rms) > 0:
        silence_threshold = np.percentile(rms, 25)
        features["low_energy_ratio"] = np.mean(rms < silence_threshold)
    else:
        features["low_energy_ratio"] = 0.0

    return features

def extract_audio_window_features(windows_dir, output_csv, sampling_rate=16000):

    rows = []

    for subject in sorted(os.listdir(windows_dir)):
        subject_dir = os.path.join(windows_dir, subject)

        if not os.path.isdir(subject_dir):
            continue

        for activity in sorted(os.listdir(subject_dir)):
            activity_dir = os.path.join(subject_dir, activity)

            if not os.path.isdir(activity_dir):
                continue

            for window_file in sorted(os.listdir(activity_dir)):
                if not window_file.lower().endswith(".wav"):
                    continue

                window_path = os.path.join(activity_dir, window_file)

                window_id = int(
                    os.path.splitext(window_file)[0].replace("window_", "")
                )

                y, sr = librosa.load(window_path, sr=sampling_rate)

                features = extract_features_from_audio(y, sr)

                rows.append({
                    "subject": subject,
                    "activity": activity.split('_')[1],
                    "window_id": window_id,
                    "subject_activity": activity,
                    **features
                })

    df = pd.DataFrame(rows)
    df.to_csv(output_csv, index=False)

    print(f"Saved features to: {output_csv}")
    print(f"Total windows processed: {len(df)}")

    return df

In [ ]:
audio_features = extract_audio_window_features(
    windows_dir="./data/5s_0overlap",
    output_csv="audio_features_5s_0overlap.csv",
    sampling_rate=16000
)

In [27]:
df_features = pd.read_csv('audio_features_5s_0overlap.csv')
df_features

,subject,activity,window_id,subject_activity,rms_mean,rms_std,zcr_mean,zcr_std,mfcc_1_mean,mfcc_1_std,...,mfcc_12_mean,mfcc_12_std,mfcc_13_mean,mfcc_13_std,pitch_mean,pitch_std,pitch_min,pitch_max,voiced_ratio,low_energy_ratio
0,2ea4,Counting1,0,2ea4_Counting1,0.024353,0.020337,0.105705,0.072654,-356.31620,151.180020,...,-11.756525,7.607572,-5.105567,10.692554,176.133509,23.820995,146.832384,241.301496,0.796178,0.248408
1,2ea4,Counting1,1,2ea4_Counting1,0.028559,0.028854,0.125883,0.074720,-355.78770,146.941590,...,-1.005276,8.748446,-6.677289,7.742668,154.764206,7.597938,135.425885,169.643191,0.573248,0.248408
2,2ea4,Counting1,2,2ea4_Counting1,0.015406,0.017756,0.143368,0.121097,-402.19458,151.004400,...,-7.368523,8.041126,-5.682947,6.806932,161.598019,7.368555,145.986692,179.730700,0.407643,0.248408
3,2ea4,Counting1,3,2ea4_Counting1,0.018954,0.014357,0.252301,0.206833,-350.57910,137.426790,...,-6.566986,9.046530,-5.721100,8.508836,179.229013,10.754735,164.813778,212.505992,0.331210,0.248408
4,2ea4,Counting1,4,2ea4_Counting1,0.019945,0.022307,0.196426,0.163529,-384.57385,140.356980,...,-6.529265,7.016305,-5.260243,8.912770,176.025027,22.264465,150.264428,222.556277,0.509554,0.248408
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3086,y9z6,Stroop,5,y9z6_Stroop,0.005253,0.003730,0.174096,0.148333,-416.65552,26.029297,...,4.814869,6.066178,-0.803817,4.724341,288.951181,11.438753,272.420799,314.742105,0.490446,0.248408
3087,y9z6,Stroop,6,y9z6_Stroop,0.005614,0.003532,0.137512,0.080529,-411.51510,21.044626,...,1.782596,5.066959,-1.944231,3.988037,289.444627,19.222600,249.810974,329.627557,0.675159,0.248408
3088,y9z6,Stroop,7,y9z6_Stroop,0.005724,0.005155,0.188439,0.141175,-413.65952,22.627660,...,2.444980,6.029319,-1.771422,5.470934,291.377745,17.634666,246.941651,327.729042,0.515924,0.248408
3089,y9z6,Stroop,8,y9z6_Stroop,0.005175,0.003828,0.190187,0.147750,-413.93054,24.514980,...,1.723448,5.382573,-2.693949,5.017823,281.451714,16.369882,263.141147,329.627557,0.515924,0.248408
3090,y9z6,Stroop,9,y9z6_Stroop,0.008048,0.006040,0.162520,0.114633,-392.80023,49.853348,...,3.168118,7.315823,-1.401565,8.284023,309.367753,17.526360,278.788334,361.543738,0.738854,0.248408

# Task level aggregation:

1. Feature level aggregation:

In [28]:
def task_aggregation(df_audio, gt):
    df = df_audio.copy()

    id_cols = ["subject", "activity", "window_id", "subject_activity"]
    feature_cols = [c for c in df.columns if c not in id_cols]

    df[feature_cols] = df[feature_cols].apply(pd.to_numeric, errors="coerce")

    # Aggregate window-level features to task level
    agg = df.groupby("subject_activity")[feature_cols].agg(["mean", "std", "max"])
    agg.columns = [f"{feat}_{stat}" for feat, stat in agg.columns]
    agg = agg.reset_index()

    # Merge with GT
    dataset = gt.merge(agg, on="subject_activity", how="inner")

    X = dataset.drop(columns=["subject_activity", "y_true"])
    y = dataset["y_true"].astype(int)

    return X, y, dataset

gt = pd.read_csv('../labels_v2.csv', sep=';').rename(columns={'subject/task':'subject_activity', 'binary-stress':'y_true'}).drop(['affect3-class', 'affect3-class-v2'], axis=1)
gt

    subject_activity  y_true
0     2ea4_Breathing       0
1     2ea4_Counting1       1
2     2ea4_Counting2       1
3     2ea4_Counting3       1
4          2ea4_Math       1
..               ...     ...
695       y9z6_Relax       0
696    y9z6_Speaking       1
697      y9z6_Stroop       1
698      y9z6_Video1       1
699      y9z6_Video2       0

[700 rows x 2 columns]

In [29]:
X, y, agg_df = task_aggregation(df_features, gt)

In [30]:
X.isna().sum()

rms_mean_mean             0
rms_mean_std             10
rms_mean_max              0
rms_std_mean              0
rms_std_std              10
                         ..
voiced_ratio_std         10
voiced_ratio_max          0
low_energy_ratio_mean     0
low_energy_ratio_std     10
low_energy_ratio_max      0
Length: 108, dtype: int64

In [31]:
nan_cols = agg_df.isna().sum()
nan_cols[nan_cols > 0].sort_values(ascending=False)

rms_mean_std            10
rms_std_std             10
zcr_mean_std            10
zcr_std_std             10
mfcc_1_mean_std         10
mfcc_1_std_std          10
mfcc_2_mean_std         10
mfcc_2_std_std          10
mfcc_3_mean_std         10
mfcc_3_std_std          10
mfcc_4_mean_std         10
mfcc_4_std_std          10
mfcc_5_mean_std         10
mfcc_5_std_std          10
mfcc_6_mean_std         10
mfcc_6_std_std          10
mfcc_7_mean_std         10
mfcc_7_std_std          10
mfcc_8_mean_std         10
mfcc_8_std_std          10
mfcc_9_mean_std         10
mfcc_9_std_std          10
mfcc_10_mean_std        10
mfcc_10_std_std         10
mfcc_11_mean_std        10
mfcc_11_std_std         10
mfcc_12_mean_std        10
mfcc_12_std_std         10
mfcc_13_mean_std        10
mfcc_13_std_std         10
pitch_mean_std          10
pitch_std_std           10
pitch_min_std           10
pitch_max_std           10
voiced_ratio_std        10
low_energy_ratio_std    10
dtype: int64

Estos son los casos en que solo se pudo extraer 1 ventana, por lo que no se pudo computar la desviacion. Podemos imputarlos con 0, refiriendo a que no hay cambios entre ventanas.

In [32]:
std_cols = [c for c in agg_df.columns if c.endswith("_std")]
agg_df[std_cols] = agg_df[std_cols].fillna(0)
X[std_cols] = X[std_cols].fillna(0)
nan_cols = agg_df.isna().sum()
nan_cols[nan_cols > 0].sort_values(ascending=False)

Series([], dtype: int64)

In [14]:
clf = Pipeline([
    ("scaler", StandardScaler()),
    ("model", LogisticRegression(max_iter=1000, class_weight="balanced"))
])

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=RANDOM_STATE)

scores = cross_validate(
    clf,
    X,
    y,
    cv=cv,
    scoring=["accuracy", "balanced_accuracy", "f1", "precision", "recall"],
)

pd.DataFrame(scores).mean()

fit_time                  0.010590
score_time                0.005618
test_accuracy             0.548364
test_balanced_accuracy    0.506808
test_f1                   0.656587
test_precision            0.722713
test_recall               0.602187
dtype: float64

In [15]:
y.value_counts(normalize=True)

y_true
1    0.717452
0    0.282548
Name: proportion, dtype: float64

In [55]:
gt

    subject_activity  y_true
0     2ea4_Breathing       0
1     2ea4_Counting1       1
2     2ea4_Counting2       1
3     2ea4_Counting3       1
4          2ea4_Math       1
..               ...     ...
695       y9z6_Relax       0
696    y9z6_Speaking       1
697      y9z6_Stroop       1
698      y9z6_Video1       1
699      y9z6_Video2       0

[700 rows x 2 columns]

In [56]:
import pandas as pd
import numpy as np
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from imblearn.ensemble import BalancedRandomForestClassifier
from xgboost import XGBClassifier
from sklearn.metrics import balanced_accuracy_score, recall_score
from sklearn.model_selection import StratifiedKFold, cross_val_predict


def task_aggregation(df_audio, gt):
    df = df_audio.copy()

    # Define ID columns so we don't try to mathematically aggregate them
    id_cols = ["subject", "activity", "window_id", "subject_activity"]
    feature_cols = [c for c in df.columns if c not in id_cols]

    # Ensure features are numeric
    df[feature_cols] = df[feature_cols].apply(pd.to_numeric, errors="coerce")

    # Group by BOTH subject_activity and subject to keep the subject ID alive
    agg = df.groupby(["subject_activity", "subject"])[feature_cols].agg(["mean", "std", "max"])
    
    # Flatten the multi-level column names (e.g., 'rms' + 'mean' -> 'rms_mean')
    agg.columns = [f"{feat}_{stat}" for feat, stat in agg.columns]
    agg = agg.reset_index()

    # Merge with your Ground Truth (which only needs subject_activity and y_true)
    dataset = gt.merge(agg, on="subject_activity", how="inner")
    
    # Extract the groups for subject-aware cross-validation splitting
    groups = dataset["subject"]

    # Drop all non-feature columns to create the clean X matrix
    X = dataset.drop(columns=["subject", "subject_activity", "y_true"])
    
    # Catch any 1-window NaN std calculations and fill them with 0
    X = X.fillna(0) 
    
    # Extract the target variable
    y = dataset["y_true"].astype(int)

    return X, y, groups, dataset


df_audio = pd.read_csv("./audio_features_5s_0overlap.csv")
gt = pd.read_csv('../labels_v2.csv', sep=';').rename(columns={'subject/task':'subject_activity', 'binary-stress':'y_true'}).drop(['affect3-class', 'affect3-class-v2'], axis=1)

X_agg, y_agg, groups_agg, full_dataset = task_aggregation(df_audio, gt)
sgkf_split = StratifiedGroupKFold(n_splits=5, shuffle=True, random_state=RANDOM_STATE)
train_idx, test_idx = next(sgkf_split.split(X_agg, y_agg, groups=groups_agg))

X_train = X_agg.iloc[train_idx]
y_train = y_agg.iloc[train_idx]
groups_train = groups_agg.iloc[train_idx]

X_test = X_agg.iloc[test_idx]
y_test = y_agg.iloc[test_idx]
groups_test = groups_agg.iloc[test_idx]

# MODELS 
# Recalculate scale weight based on the NEW aggregated class balance
scale_weight = (y_train_agg == 0).sum() / (y_train_agg == 1).sum()

models = {
    "Logistic Regression": make_pipeline(
        StandardScaler(), 
        LogisticRegression(class_weight='balanced', max_iter=2000, random_state=RANDOM_STATE)
    ),
    "Balanced Random Forest": make_pipeline(
        BalancedRandomForestClassifier(n_estimators=100, sampling_strategy='auto', random_state=RANDOM_STATE, n_jobs=-1)
    ),
    "XGBoost": make_pipeline(
        XGBClassifier(scale_pos_weight=scale_weight, eval_metric='logloss', random_state=RANDOM_STATE, n_jobs=-1)
    ),
    "Random Forest": RandomForestClassifier(
        class_weight="balanced", n_estimators=100, random_state=RANDOM_STATE, n_jobs=-1
    ), 
}


cv_train = StratifiedKFold(n_splits=5, shuffle=True, random_state=RANDOM_STATE)
results_list = []

for model_name, model in models.items():
    
    # Get out-of-fold probabilities for threshold tuning using the AGGREGATED train set
    train_unbiased_probs = cross_val_predict(
        model, X_train_agg, y_train_agg, 
        cv=cv_train, 
        method='predict_proba',
        n_jobs=-1
    )[:, 1]
    
    best_thresh = 0.5
    best_b_acc = 0
    
    for thresh in np.arange(0.1, 0.9, 0.02):
        train_preds = (train_unbiased_probs >= thresh).astype(int)
        b_acc = balanced_accuracy_score(y_train_agg, train_preds)
        if b_acc >= best_b_acc: 
            best_b_acc = b_acc
            best_thresh = thresh
            
    # Train final model on the full aggregated training data
    model.fit(X_train_agg, y_train_agg)
    
    # Predict on the aggregated test set
    test_probs = model.predict_proba(X_test_agg)[:, 1]
    
    # Apply optimal threshold and evaluate
    test_preds = (test_probs >= best_thresh).astype(int)
    
    final_b_acc = balanced_accuracy_score(y_test_agg, test_preds)
    acc = accuracy_score(y_test_agg, test_preds)
    f1 = f1_score(y_test_agg, test_preds)
    recall_0 = recall_score(y_test_agg, test_preds, pos_label=0, zero_division=0)
    recall_1 = recall_score(y_test_agg, test_preds, pos_label=1, zero_division=0)
    precision = precision_score(y_test_agg, test_preds)
    
    results_list.append({
        "Model": model_name,
        "Thresh": round(best_thresh, 2),
        "Bal_Acc": round(final_b_acc, 4),
        "Accuracy": round(acc, 2),
        "F1": round(f1,2),
        "Rec_Relaxed": round(recall_0, 2),
        "Rec_Stress": round(recall_1, 2),
        "Precision": round(precision, 2)
    })

comparison_df = pd.DataFrame(results_list)
comparison_df = comparison_df.sort_values(by="Bal_Acc", ascending=False).reset_index(drop=True)

print(comparison_df.to_string(index=False))

                 Model  Thresh  Bal_Acc  Accuracy   F1  Rec_Relaxed  Rec_Stress  Precision
Balanced Random Forest    0.38   0.6090      0.73 0.82         0.35        0.87       0.78
         Random Forest    0.76   0.5698      0.47 0.48         0.80        0.34       0.82
               XGBoost    0.88   0.5642      0.55 0.63         0.60        0.53       0.78
   Logistic Regression    0.26   0.5090      0.67 0.79         0.15        0.87       0.73

# Decision-Level Aggregation

## Undersampling

In [ ]:
from imblearn.under_sampling import RandomUnderSampler

rus = RandomUnderSampler(random_state=123)

# Undersample the training data
X_train_resampled, y_train_resampled = rus.fit_resample(X_train, y_train)

# Train the model on the perfectly balanced training data
clf = RandomForestClassifier(n_estimators=100, random_state=RANDOM_STATE, n_jobs=-1)
clf.fit(X_train_resampled, y_train_resampled)

window_pred_probs = clf.predict_proba(X_test)[:, 1]


# Decision level aggregation
test_results_df = pd.DataFrame({
    "subject_activity": groups_test,
    "true_label": y_test,
    "pred_prob": window_pred_probs
})

# Aggregate probabilities by task
task_results = test_results_df.groupby("subject_activity").agg(
    true_label=("true_label", "first"),
    mean_prob=("pred_prob", "mean")
).reset_index()

task_results["pred_label"] = (task_results["mean_prob"] >= 0.5).astype(int)


# Final Evaluation
print(classification_report(task_results["true_label"], task_results["pred_label"]))

# Using scikit-learn's built-in balanced accuracy metric
b_acc = balanced_accuracy_score(task_results["true_label"], task_results["pred_label"])
print(f"Task-Level Balanced Accuracy: {b_acc:.4f}")

              precision    recall  f1-score   support

           0       0.46      0.60      0.52        20
           1       0.83      0.74      0.78        53

    accuracy                           0.70        73
   macro avg       0.65      0.67      0.65        73
weighted avg       0.73      0.70      0.71        73

Task-Level Balanced Accuracy: 0.6679

In [19]:
merged_df[merged_df['binary-stress'] == 0]['activity'].value_counts()

activity
Reading      238
Counting3    134
Counting1    130
Speaking     128
Math         110
Counting2     92
Stroop        61
Name: count, dtype: int64

In [20]:
# Import the balanced classifier
from imblearn.ensemble import BalancedRandomForestClassifier


sgkf = StratifiedGroupKFold(n_splits=5, shuffle=True, random_state=RANDOM_STATE)

train_idx, test_idx = next(sgkf.split(X, y, groups))

X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]
y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]
groups_test = groups.iloc[test_idx]

clf = BalancedRandomForestClassifier(
    n_estimators=100, 
    random_state=RANDOM_STATE, 
    n_jobs=-1,
    sampling_strategy='auto' 
)

clf.fit(X_train, y_train)
window_pred_probs = clf.predict_proba(X_test)[:, 1]


test_results_df = pd.DataFrame({
    "subject_activity": groups_test,
    "true_label": y_test,
    "pred_prob": window_pred_probs
})

# Aggregate probabilities by task
task_results = test_results_df.groupby("subject_activity").agg(
    true_label=("true_label", "first"),
    mean_prob=("pred_prob", "mean")
).reset_index()

# Apply the threshold to get binary predictions
task_results["pred_label"] = (task_results["mean_prob"] >= 0.5).astype(int)


print(classification_report(task_results["true_label"], task_results["pred_label"]))

b_acc = balanced_accuracy_score(task_results["true_label"], task_results["pred_label"])
print(f"Task-Level Balanced Accuracy: {b_acc:.4f}")

              precision    recall  f1-score   support

           0       0.39      0.70      0.50        20
           1       0.84      0.58      0.69        53

    accuracy                           0.62        73
   macro avg       0.61      0.64      0.59        73
weighted avg       0.71      0.62      0.64        73

Task-Level Balanced Accuracy: 0.6425

## Decision level Agregation methods tuning

In [51]:
features_df = pd.read_csv("./audio_features_5s_0overlap.csv")
gt_df = pd.read_csv("../labels_v2.csv", sep=";")

merged_df = pd.merge(
    features_df, 
    gt_df, 
    left_on="subject_activity", 
    right_on="subject/task", 
    how="inner"
)

# feature columns and target
exclude_cols = [
    "subject", "activity", "window_id", "subject_activity", 
    "subject/task", "binary-stress", "affect3-class", "affect3-class-v2"
]
feature_cols = [col for col in merged_df.columns if col not in exclude_cols]

X = merged_df[feature_cols]
y = merged_df["binary-stress"]
groups = merged_df["subject_activity"]

# Stratified Group Splitting
sgkf = StratifiedGroupKFold(n_splits=5, shuffle=True, random_state=RANDOM_STATE)

# next() to grab just the first split 
train_idx, test_idx = next(sgkf.split(X, y, groups))

X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]
y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]
groups_test = groups.iloc[test_idx]

In [52]:
# Models
# # Note: XGBoost uses 'scale_pos_weight' for imbalance. Since Class 1 (Stress) 
# is the majority class, we calculate the ratio of Class 0 to Class 1.
scale_weight = (y_train == 0).sum() / (y_train == 1).sum()

models = {
    "Logistic Regression": make_pipeline(
        StandardScaler(), 
        LogisticRegression(class_weight='balanced', max_iter=2000, random_state=RANDOM_STATE)
    ),
    "Balanced Random Forest": make_pipeline(
        BalancedRandomForestClassifier(n_estimators=100, sampling_strategy='auto', random_state=RANDOM_STATE, n_jobs=-1)
    ),
    "XGBoost": make_pipeline(
        XGBClassifier(scale_pos_weight=scale_weight, eval_metric='logloss', random_state=RANDOM_STATE, n_jobs=-1)
    ),
    "Random Forest":
        RandomForestClassifier(
            class_weight="balanced",
            n_estimators=100,
            random_state=RANDOM_STATE,
            n_jobs=-1
    ), 
}

agg_strategies = {
    "Mean": "mean",
    "Median": "median",
    "Max": "max",
    "75th_Percentile": lambda x: np.percentile(x, 75)
}

cv_train = StratifiedGroupKFold(n_splits=5, shuffle=True, random_state=RANDOM_STATE)
results_list = []


for model_name, model in models.items():
    
    model.fit(X_train, y_train)
    test_probs = model.predict_proba(X_test)[:, 1]
    
    # Get out-of-fold probabilities for threshold tuning
    train_unbiased_probs = cross_val_predict(
        model, X_train, y_train, 
        groups=groups.iloc[train_idx], 
        cv=cv_train, 
        method='predict_proba',
        n_jobs=-1
    )[:, 1]
    
    train_base_df = pd.DataFrame({
        "subject_activity": groups.iloc[train_idx].values,
        "true_label": y_train.values,
        "pred_prob": train_unbiased_probs 
    })
    
    test_base_df = pd.DataFrame({
        "subject_activity": groups_test.values,
        "true_label": y_test.values,
        "pred_prob": test_probs 
    })

    for strategy_name, agg_func in agg_strategies.items():
        
        train_agg = train_base_df.groupby("subject_activity").agg(
            true_label=("true_label", "first"),
            agg_prob=("pred_prob", agg_func)
        ).reset_index()
        
        # Tune Threshold
        best_thresh = 0.5
        best_b_acc = 0
        for thresh in np.arange(0.1, 0.9, 0.02):
            train_preds = (train_agg["agg_prob"] >= thresh).astype(int)
            b_acc = balanced_accuracy_score(train_agg["true_label"], train_preds)
            if b_acc >= best_b_acc: 
                best_b_acc = b_acc
                best_thresh = thresh
                
        test_agg = test_base_df.groupby("subject_activity").agg(
            true_label=("true_label", "first"),
            agg_prob=("pred_prob", agg_func)
        ).reset_index()
        
        # Apply Threshold and Evaluate
        test_preds = (test_agg["agg_prob"] >= best_thresh).astype(int)
        final_b_acc = balanced_accuracy_score(test_agg["true_label"], test_preds)
        acc = accuracy_score(test_agg["true_label"], test_preds)
        f1 = f1_score(test_agg["true_label"], test_preds)
        recall_0 = recall_score(test_agg["true_label"], test_preds, pos_label=0, zero_division=0)
        recall_1 = recall_score(test_agg["true_label"], test_preds, pos_label=1, zero_division=0)
        precision = precision_score(test_agg["true_label"], test_preds)
        
        results_list.append({
            "Model": model_name,
            "Strategy": strategy_name,
            "Thresh": round(best_thresh, 2),
            "Bal_Acc": round(final_b_acc, 4),
            "Accuracy": round(acc,2),
            "F1": round(f1,2),
            "Rec_Relaxed": round(recall_0, 2),
            "Rec_Stress": round(recall_1, 2),
            "Precision": round(precision, 2)
        })

comparison_df = pd.DataFrame(results_list)
comparison_df = comparison_df.sort_values(by="Bal_Acc", ascending=False).reset_index(drop=True)

print(comparison_df.to_string(index=False))

                 Model        Strategy  Thresh  Bal_Acc  Accuracy   F1  Rec_Relaxed  Rec_Stress  Precision
               XGBoost          Median    0.82   0.6835      0.70 0.78         0.65        0.72       0.84
Balanced Random Forest          Median    0.54   0.6642      0.60 0.66         0.80        0.53       0.88
               XGBoost             Max    0.88   0.6623      0.78 0.86         0.40        0.92       0.80
               XGBoost 75th_Percentile    0.88   0.6618      0.71 0.80         0.55        0.77       0.82
Balanced Random Forest            Mean    0.54   0.6453      0.58 0.63         0.80        0.49       0.87
Balanced Random Forest 75th_Percentile    0.56   0.6425      0.62 0.69         0.70        0.58       0.84
   Logistic Regression 75th_Percentile    0.48   0.6401      0.73 0.81         0.45        0.83       0.80
         Random Forest          Median    0.74   0.6392      0.59 0.65         0.75        0.53       0.85
         Random Forest 75th_Percentile    0.74   0.6368      0.70 0.79         0.50        0.77       0.80
         Random Forest            Mean    0.74   0.6297      0.58 0.64         0.75        0.51       0.84
               XGBoost            Mean    0.76   0.6146      0.64 0.73         0.55        0.68       0.80
         Random Forest             Max    0.82   0.6019      0.60 0.69         0.60        0.60       0.80
Balanced Random Forest             Max    0.68   0.5825      0.51 0.55         0.75        0.42       0.81
   Logistic Regression            Mean    0.52   0.5486      0.55 0.64         0.55        0.55       0.76
   Logistic Regression             Max    0.78   0.5321      0.41 0.39         0.80        0.26       0.78
   Logistic Regression          Median    0.52   0.5108      0.49 0.57         0.55        0.47       0.74

# Audio Embeddings

## Wav2Vec 2.0:

In [ ]:
import os
import pandas as pd
import numpy as np
import torch
import torchaudio
from transformers import Wav2Vec2Processor, Wav2Vec2Model
from tqdm import tqdm
from huggingface_hub import login

AUDIO_WINDOWS_DIR = "./data/5s_0overlap"
GROUND_TRUTH_CSV = "../labels_v2.csv"

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

login('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')
model_name = "facebook/wav2vec2-base"
processor = Wav2Vec2Processor.from_pretrained(model_name)
model = Wav2Vec2Model.from_pretrained(model_name).to(device)
model.eval()

target_sample_rate = 16000
embedding_list = []

print("Crawling directories and extracting Wav2Vec 2.0 embeddings...")

with torch.no_grad():
    for subject in tqdm(sorted(os.listdir(AUDIO_WINDOWS_DIR)), desc="Subjects"):
        subject_dir = os.path.join(AUDIO_WINDOWS_DIR, subject)
        if not os.path.isdir(subject_dir): continue
            
        for activity in sorted(os.listdir(subject_dir)):
            activity_dir = os.path.join(subject_dir, activity)
            if not os.path.isdir(activity_dir): continue
                
            subject_activity = f"{subject}_{activity}"
            
            for window_file in sorted(os.listdir(activity_dir)):
                if not window_file.lower().endswith(".wav"): continue
                    
                window_id = int(window_file.split("_")[1].split(".")[0])
                file_path = os.path.join(activity_dir, window_file)
                
                waveform, sample_rate = torchaudio.load(file_path)
                if waveform.shape[0] > 1:
                    waveform = torch.mean(waveform, dim=0, keepdim=True)
                    
                if sample_rate != target_sample_rate:
                    resampler = torchaudio.transforms.Resample(orig_freq=sample_rate, new_freq=target_sample_rate)
                    waveform = resampler(waveform)
                    
                inputs = processor(waveform.squeeze().numpy(), sampling_rate=target_sample_rate, return_tensors="pt")
                inputs = {key: val.to(device) for key, val in inputs.items()}
                outputs = model(**inputs)
                
                mean_pooled_embedding = outputs.last_hidden_state.mean(dim=1).squeeze().cpu().numpy()
                
                row_data = {
                    "subject": subject,
                    "activity": activity,
                    "subject_activity": subject_activity,
                    "window_id": window_id
                }
                
                for i, val in enumerate(mean_pooled_embedding):
                    row_data[f"w2v_{i}"] = val
                    
                embedding_list.append(row_data)

embeddings_df = pd.DataFrame(embedding_list)

gt_df = pd.read_csv(GROUND_TRUTH_CSV, sep=";")

merged_df = pd.merge(
    embeddings_df, 
    gt_df, 
    left_on="subject_activity", 
    right_on="subject/task", 
    how="inner"
)

merged_df.to_csv("wav2vec_embeddings.csv", index=False)
print(f"Extraction complete! Saved {len(merged_df)} windows to {output_csv}.")

Using device: cpu

Loading weights: 100%|██████████| 211/211 [00:00<00:00, 60101.74it/s]
[transformers] Wav2Vec2Model LOAD REPORT from: facebook/wav2vec2-base
Key                          | Status     |  |
-----------------------------+------------+--+-
project_hid.weight           | UNEXPECTED |  |
project_q.bias               | UNEXPECTED |  |
project_q.weight             | UNEXPECTED |  |
quantizer.weight_proj.weight | UNEXPECTED |  |
quantizer.weight_proj.bias   | UNEXPECTED |  |
quantizer.codevectors        | UNEXPECTED |  |
project_hid.bias             | UNEXPECTED |  |

Notes:
- UNEXPECTED:	can be ignored when loading from different task/architecture; not ok if you expect identical arch.

Crawling directories and extracting Wav2Vec 2.0 embeddings...

Subjects: 100%|██████████| 54/54 [09:46<00:00, 10.86s/it]

Merging with ground truth labels...
Extraction complete! Saved 0 windows to wav2vec_embeddings.csv.

In [10]:
embeddings_df['activity'] = embeddings_df['activity'].apply(lambda x: x.split('_')[1])
embeddings_df['subject_activity'] = embeddings_df['subject_activity'].apply(lambda x: "_".join(x.split('_')[1:3]))

In [11]:
merged_df = pd.merge(
    embeddings_df, 
    gt_df, 
    left_on="subject_activity", 
    right_on="subject/task", 
    how="inner"
)

In [13]:
merged_df.to_csv("wav2vec_embeddings.csv", index=False)

In [57]:
import warnings

# Suppress minor warnings for clean output
warnings.filterwarnings("ignore")

df = pd.read_csv("wav2vec_embeddings.csv")

# Extract features, target, and groups
X = df.filter(regex='^w2v_')
y = df["binary-stress"]
groups = df["subject_activity"]

sgkf = StratifiedGroupKFold(n_splits=5, shuffle=True, random_state=42)
train_idx, test_idx = next(sgkf.split(X, y, groups))

X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]
y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]

# Calculate imbalance weight for XGBoost
scale_weight = (y_train == 0).sum() / (y_train == 1).sum()

# Define Models
models = {
    "Logistic Regression": make_pipeline(
        StandardScaler(), 
        LogisticRegression(class_weight='balanced', max_iter=2000, random_state=RANDOM_STATE)
    ),
    "Balanced Random Forest": make_pipeline(
        BalancedRandomForestClassifier(n_estimators=100, sampling_strategy='auto', random_state=RANDOM_STATE, n_jobs=-1)
    ),
    "XGBoost": make_pipeline(
        XGBClassifier(scale_pos_weight=scale_weight, eval_metric='logloss', random_state=RANDOM_STATE, n_jobs=-1)
    ),
    "Random Forest": RandomForestClassifier(
        class_weight="balanced", n_estimators=100, random_state=RANDOM_STATE, n_jobs=-1
    ), 
}

agg_strategies = {
    "Mean": "mean",
    "Median": "median",
    "Max": "max",
    "75th_Percentile": lambda x: np.percentile(x, 75)
}

cv_train = StratifiedGroupKFold(n_splits=3, shuffle=True, random_state=42)
results_list = []


for model_name, model in models.items():
    
    # Train and predict
    model.fit(X_train, y_train)
    test_probs = model.predict_proba(X_test)[:, 1]
    
    # Out-of-fold probabilities for unbiased threshold tuning
    train_unbiased_probs = cross_val_predict(
        model, X_train, y_train, 
        groups=groups.iloc[train_idx], 
        cv=cv_train, 
        method='predict_proba',
        n_jobs=-1
    )[:, 1]
    
    train_base_df = pd.DataFrame({
        "subject_activity": groups.iloc[train_idx].values,
        "true_label": y_train.values,
        "pred_prob": train_unbiased_probs 
    })
    
    test_base_df = pd.DataFrame({
        "subject_activity": groups.iloc[test_idx].values,
        "true_label": y_test.values,
        "pred_prob": test_probs 
    })

    # Test Aggregation Strategies
    for strategy_name, agg_func in agg_strategies.items():
        
        train_agg = train_base_df.groupby("subject_activity").agg(
            true_label=("true_label", "first"),
            agg_prob=("pred_prob", agg_func)
        ).reset_index()
        
        best_thresh = 0.5
        best_b_acc = 0
        for thresh in np.arange(0.1, 0.9, 0.02):
            train_preds = (train_agg["agg_prob"] >= thresh).astype(int)
            b_acc = balanced_accuracy_score(train_agg["true_label"], train_preds)
            if b_acc >= best_b_acc: 
                best_b_acc = b_acc
                best_thresh = thresh
                
        test_agg = test_base_df.groupby("subject_activity").agg(
            true_label=("true_label", "first"),
            agg_prob=("pred_prob", agg_func)
        ).reset_index()
        
        test_preds = (test_agg["agg_prob"] >= best_thresh).astype(int)
        final_b_acc = balanced_accuracy_score(test_agg["true_label"], test_preds)
        acc = accuracy_score(test_agg["true_label"], test_preds)
        f1 = f1_score(test_agg["true_label"], test_preds)
        recall_0 = recall_score(test_agg["true_label"], test_preds, pos_label=0, zero_division=0)
        recall_1 = recall_score(test_agg["true_label"], test_preds, pos_label=1, zero_division=0)
        precision = precision_score(test_agg["true_label"], test_preds)
        
        results_list.append({
            "Model": model_name,
            "Strategy": strategy_name,
            "Thresh": round(best_thresh, 2),
            "Bal_Acc": round(final_b_acc, 4),
            "Accuracy": round(acc, 2),
            "F1": round(f1, 2),
            "Rec_Relaxed": round(recall_0, 2),
            "Rec_Stress": round(recall_1, 2),
            "Precision": round(precision, 2)
        })

comparison_df = pd.DataFrame(results_list)
comparison_df = comparison_df.sort_values(by="Bal_Acc", ascending=False).reset_index(drop=True)

print("\n=== Wav2Vec 2.0 Results ===")
print(comparison_df.to_string(index=False))

=== Wav2Vec 2.0 Results ===
                 Model        Strategy  Thresh  Bal_Acc  Accuracy   F1  Rec_Relaxed  Rec_Stress  Precision
         Random Forest          Median    0.72   0.6369      0.68 0.77         0.52        0.75       0.80
   Logistic Regression          Median    0.56   0.6277      0.71 0.80         0.43        0.83       0.78
               XGBoost            Mean    0.70   0.6277      0.71 0.80         0.43        0.83       0.78
         Random Forest 75th_Percentile    0.72   0.6232      0.73 0.82         0.38        0.87       0.78
Balanced Random Forest 75th_Percentile    0.56   0.6172      0.62 0.70         0.62        0.62       0.80
   Logistic Regression            Mean    0.60   0.5989      0.67 0.77         0.43        0.77       0.77
         Random Forest            Mean    0.72   0.5984      0.63 0.72         0.52        0.67       0.78
         Random Forest             Max    0.86   0.5975      0.55 0.60         0.71        0.48       0.81
Balanced Random Forest             Max    0.66   0.5934      0.60 0.69         0.57        0.62       0.78
Balanced Random Forest          Median    0.42   0.5897      0.70 0.80         0.33        0.85       0.76
   Logistic Regression 75th_Percentile    0.76   0.5897      0.70 0.80         0.33        0.85       0.76
   Logistic Regression             Max    0.88   0.5856      0.75 0.85         0.19        0.98       0.75
               XGBoost 75th_Percentile    0.86   0.5852      0.71 0.81         0.29        0.88       0.75
               XGBoost          Median    0.76   0.5563      0.67 0.78         0.29        0.83       0.74
               XGBoost             Max    0.88   0.5522      0.73 0.83         0.14        0.96       0.74
Balanced Random Forest            Mean    0.40   0.5472      0.70 0.81         0.19        0.90       0.73

## HuBert

In [ ]:
from transformers import Wav2Vec2FeatureExtractor, HubertModel
from tqdm import tqdm

AUDIO_WINDOWS_DIR = "./data/5s_0overlap" 
GROUND_TRUTH_CSV = "../labels_v2.csv"

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

model_name = "facebook/hubert-base-ls960"
# HuBERT uses the same feature extractor logic as Wav2Vec2 for raw audio
processor = Wav2Vec2FeatureExtractor.from_pretrained(model_name)
model = HubertModel.from_pretrained(model_name).to(device)
model.eval()

target_sample_rate = 16000
embedding_list = []

print("Extracting HuBERT embeddings...")

with torch.no_grad():
    for subject in tqdm(sorted(os.listdir(AUDIO_WINDOWS_DIR)), desc="Subjects"):
        subject_dir = os.path.join(AUDIO_WINDOWS_DIR, subject)
        if not os.path.isdir(subject_dir): continue
            
        for subject_activity in sorted(os.listdir(subject_dir)):
            activity_dir = os.path.join(subject_dir, subject_activity)
            if not os.path.isdir(activity_dir): continue
                
            # Using the fix we established earlier
            activity = subject_activity.split('_')[1]
            
            for window_file in sorted(os.listdir(activity_dir)):
                if not window_file.lower().endswith(".wav"): continue
                    
                window_id = int(window_file.split("_")[1].split(".")[0])
                file_path = os.path.join(activity_dir, window_file)
                
                # Load audio
                waveform, sample_rate = torchaudio.load(file_path)
                if waveform.shape[0] > 1:
                    waveform = torch.mean(waveform, dim=0, keepdim=True)
                    
                if sample_rate != target_sample_rate:
                    resampler = torchaudio.transforms.Resample(orig_freq=sample_rate, new_freq=target_sample_rate)
                    waveform = resampler(waveform)
                    
                # Process and Forward Pass
                inputs = processor(waveform.squeeze().numpy(), sampling_rate=target_sample_rate, return_tensors="pt")
                inputs = {key: val.to(device) for key, val in inputs.items()}
                outputs = model(**inputs)
                
                # Temporal Pooling
                mean_pooled_embedding = outputs.last_hidden_state.mean(dim=1).squeeze().cpu().numpy()
                
                # Store results
                row_data = {
                    "subject": subject,
                    "activity": activity,
                    "subject_activity": subject_activity,
                    "window_id": window_id
                }
                
                # Use 'hubert_' prefix just to keep things clean
                for i, val in enumerate(mean_pooled_embedding):
                    row_data[f"hubert_{i}"] = val
                    
                embedding_list.append(row_data)

embeddings_df = pd.DataFrame(embedding_list)

print("Merging with ground truth labels...")
gt_df = pd.read_csv(GROUND_TRUTH_CSV, sep=";")

merged_df = pd.merge(
    embeddings_df, 
    gt_df, 
    left_on="subject_activity", 
    right_on="subject/task", 
    how="inner"
)

output_csv = "hubert_embeddings.csv"
merged_df.to_csv(output_csv, index=False)
print(f"Extraction complete! Saved {len(merged_df)} windows to {output_csv}.")

Using device: cpu

Loading weights: 100%|██████████| 211/211 [00:00<00:00, 47230.13it/s]

Extracting HuBERT embeddings...

Subjects: 100%|██████████| 54/54 [09:46<00:00, 10.86s/it]

Merging with ground truth labels...
Extraction complete! Saved 3091 windows to hubert_embeddings.csv.

In [ ]:


df = pd.read_csv("hubert_embeddings.csv")

# Extract features, target, and groups
X = df.filter(regex='^hubert_')
y = df["binary-stress"]
groups = df["subject_activity"]

sgkf = StratifiedGroupKFold(n_splits=5, shuffle=True, random_state=42)
train_idx, test_idx = next(sgkf.split(X, y, groups))

X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]
y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]

# Calculate imbalance weight for XGBoost
scale_weight = (y_train == 0).sum() / (y_train == 1).sum()

# 3. Define Models (Same as classical baseline)
models = {
    "Logistic Regression": make_pipeline(
        StandardScaler(), 
        LogisticRegression(class_weight='balanced', max_iter=2000, random_state=42)
    ),
    "Balanced Random Forest": make_pipeline(
        StandardScaler(),
        BalancedRandomForestClassifier(n_estimators=100, sampling_strategy='auto', random_state=42, n_jobs=-1)
    ),
    "XGBoost": make_pipeline(
        StandardScaler(),
        XGBClassifier(scale_pos_weight=scale_weight, eval_metric='logloss', random_state=42, n_jobs=-1)
    ),
    "Random Forest": RandomForestClassifier(
        class_weight="balanced", n_estimators=100, random_state=RANDOM_STATE, n_jobs=-1
    ), 
}

agg_strategies = {
    "Mean": "mean",
    "Median": "median",
    "Max": "max",
    "75th_Percentile": lambda x: np.percentile(x, 75)
}

cv_train = StratifiedGroupKFold(n_splits=3, shuffle=True, random_state=42)
results_list = []


for model_name, model in models.items():
    
    # Train and predict
    model.fit(X_train, y_train)
    test_probs = model.predict_proba(X_test)[:, 1]
    
    # Out-of-fold probabilities for unbiased threshold tuning
    train_unbiased_probs = cross_val_predict(
        model, X_train, y_train, 
        groups=groups.iloc[train_idx], 
        cv=cv_train, 
        method='predict_proba',
        n_jobs=-1
    )[:, 1]
    
    train_base_df = pd.DataFrame({
        "subject_activity": groups.iloc[train_idx].values,
        "true_label": y_train.values,
        "pred_prob": train_unbiased_probs 
    })
    
    test_base_df = pd.DataFrame({
        "subject_activity": groups.iloc[test_idx].values,
        "true_label": y_test.values,
        "pred_prob": test_probs 
    })

    # Test Aggregation Strategies
    for strategy_name, agg_func in agg_strategies.items():
        
        train_agg = train_base_df.groupby("subject_activity").agg(
            true_label=("true_label", "first"),
            agg_prob=("pred_prob", agg_func)
        ).reset_index()
        
        best_thresh = 0.5
        best_b_acc = 0
        for thresh in np.arange(0.1, 0.9, 0.02):
            train_preds = (train_agg["agg_prob"] >= thresh).astype(int)
            b_acc = balanced_accuracy_score(train_agg["true_label"], train_preds)
            if b_acc >= best_b_acc: 
                best_b_acc = b_acc
                best_thresh = thresh
                
        test_agg = test_base_df.groupby("subject_activity").agg(
            true_label=("true_label", "first"),
            agg_prob=("pred_prob", agg_func)
        ).reset_index()
        
        test_preds = (test_agg["agg_prob"] >= best_thresh).astype(int)
        final_b_acc = balanced_accuracy_score(test_agg["true_label"], test_preds)
        acc = accuracy_score(test_agg["true_label"], test_preds)
        f1 = f1_score(test_agg["true_label"], test_preds)
        recall_0 = recall_score(test_agg["true_label"], test_preds, pos_label=0, zero_division=0)
        recall_1 = recall_score(test_agg["true_label"], test_preds, pos_label=1, zero_division=0)
        precision = precision_score(test_agg["true_label"], test_preds)
        
        results_list.append({
            "Model": model_name,
            "Strategy": strategy_name,
            "Thresh": round(best_thresh, 2),
            "Bal_Acc": round(final_b_acc, 4),
            "Accuracy": round(acc, 2),
            "F1": round(f1, 2),
            "Rec_Relaxed": round(recall_0, 2),
            "Rec_Stress": round(recall_1, 2),
            "Precision": round(precision, 2)
        })

comparison_df = pd.DataFrame(results_list)
comparison_df = comparison_df.sort_values(by="Bal_Acc", ascending=False).reset_index(drop=True)

print("\n=== Hubert Results ===")
print(comparison_df.to_string(index=False))

=== Hubert Results ===
                 Model        Strategy  Thresh  Bal_Acc  Accuracy   F1  Rec_Relaxed  Rec_Stress  Precision
Balanced Random Forest 75th_Percentile    0.48   0.6516      0.73 0.81         0.48        0.83       0.80
Balanced Random Forest          Median    0.44   0.6277      0.71 0.80         0.43        0.83       0.78
         Random Forest            Mean    0.72   0.6273      0.67 0.76         0.52        0.73       0.79
   Logistic Regression 75th_Percentile    0.86   0.6227      0.68 0.78         0.48        0.77       0.78
         Random Forest          Median    0.70   0.6227      0.68 0.78         0.48        0.77       0.78
Balanced Random Forest             Max    0.56   0.6085      0.68 0.78         0.43        0.79       0.77
   Logistic Regression            Mean    0.64   0.6076      0.60 0.68         0.62        0.60       0.79
Balanced Random Forest            Mean    0.40   0.5902      0.74 0.84         0.24        0.94       0.75
   Logistic Regression          Median    0.86   0.5737      0.53 0.60         0.67        0.48       0.78
         Random Forest 75th_Percentile    0.72   0.5659      0.68 0.79         0.29        0.85       0.75
               XGBoost             Max    0.88   0.5618      0.74 0.84         0.14        0.98       0.74
   Logistic Regression             Max    0.74   0.5426      0.71 0.82         0.14        0.94       0.73
               XGBoost 75th_Percentile    0.86   0.5229      0.64 0.76         0.24        0.81       0.72
               XGBoost            Mean    0.62   0.5087      0.64 0.77         0.19        0.83       0.72
               XGBoost          Median    0.86   0.5078      0.56 0.67         0.38        0.63       0.72
         Random Forest             Max    0.86   0.5060      0.40 0.37         0.76        0.25       0.72

## AST

Vision Transformer applied on audio, which is turned into a spectrogram (an image).

In [ ]:
from transformers import ASTFeatureExtractor, ASTModel
from tqdm import tqdm

AUDIO_WINDOWS_DIR = "./data/5s_0overlap" 
GROUND_TRUTH_CSV = "../labels_v2.csv"

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(f"Using device: {device}")

# We use the standard AST model fine-tuned on AudioSet
login('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')

model_name = "MIT/ast-finetuned-audioset-10-10-0.4593"
processor = ASTFeatureExtractor.from_pretrained(model_name)
model = ASTModel.from_pretrained(model_name).to(device)
model.eval() # Freeze the model

target_sample_rate = 16000
embedding_list = []

print("Extracting AST embeddings...")

# 3. Extraction Loop
with torch.no_grad():
    for subject in tqdm(sorted(os.listdir(AUDIO_WINDOWS_DIR)), desc="Subjects"):
        subject_dir = os.path.join(AUDIO_WINDOWS_DIR, subject)
        if not os.path.isdir(subject_dir): continue
            
        for subject_activity in sorted(os.listdir(subject_dir)):
            activity_dir = os.path.join(subject_dir, activity)
            if not os.path.isdir(activity_dir): continue
                
            # Using the established fix for the ID
            activity = subject_activity.split("_")[1]
            
            for window_file in sorted(os.listdir(activity_dir)):
                if not window_file.lower().endswith(".wav"): continue
                    
                window_id = int(window_file.split("_")[1].split(".")[0])
                file_path = os.path.join(activity_dir, window_file)
                
                # Load audio
                waveform, sample_rate = torchaudio.load(file_path)
                if waveform.shape[0] > 1:
                    waveform = torch.mean(waveform, dim=0, keepdim=True)
                    
                if sample_rate != target_sample_rate:
                    resampler = torchaudio.transforms.Resample(orig_freq=sample_rate, new_freq=target_sample_rate)
                    waveform = resampler(waveform)
                    
                # Process and Forward Pass
                # AST expects the raw waveform and handles the spectrogram conversion internally
                inputs = processor(waveform.squeeze().numpy(), sampling_rate=target_sample_rate, return_tensors="pt")
                inputs = {key: val.to(device) for key, val in inputs.items()}
                outputs = model(**inputs)
                
                # Temporal/Patch Pooling
                # AST outputs sequence of patches. We take the mean across the sequence.
                mean_pooled_embedding = outputs.last_hidden_state.mean(dim=1).squeeze().cpu().numpy()
                
                # Store results
                row_data = {
                    "subject": subject,
                    "activity": activity,
                    "subject_activity": subject_activity,
                    "window_id": window_id
                }
                
                # Prefix with 'ast_'
                for i, val in enumerate(mean_pooled_embedding):
                    row_data[f"ast_{i}"] = val
                    
                embedding_list.append(row_data)

# 4. Create DataFrame and Merge with Ground Truth
embeddings_df = pd.DataFrame(embedding_list)

print("Merging with ground truth labels...")
gt_df = pd.read_csv(GROUND_TRUTH_CSV, sep=";")

merged_df = pd.merge(
    embeddings_df, 
    gt_df, 
    left_on="subject_activity", 
    right_on="subject/task", 
    how="inner"
)

output_csv = "ast_embeddings.csv"
merged_df.to_csv(output_csv, index=False)
print(f"Extraction complete! Saved {len(merged_df)} windows to {output_csv}.")

Using device: cpu

Cancellation requested; stopping current tasks.

KeyboardInterrupt:

In [62]:

df = pd.read_csv("ast_embeddings.csv")

# Extract features, target, and groups
X = df.filter(regex='^ast_')
y = df["binary-stress"]
groups = df["subject_activity"]

sgkf = StratifiedGroupKFold(n_splits=5, shuffle=True, random_state=42)
train_idx, test_idx = next(sgkf.split(X, y, groups))

X_train, X_test = X.iloc[train_idx], X.iloc[test_idx]
y_train, y_test = y.iloc[train_idx], y.iloc[test_idx]

# Calculate imbalance weight for XGBoost
scale_weight = (y_train == 0).sum() / (y_train == 1).sum()

models = {
    "Logistic Regression": make_pipeline(
        StandardScaler(), 
        LogisticRegression(class_weight='balanced', max_iter=2000, random_state=42)
    ),
    "Balanced Random Forest": make_pipeline(
        StandardScaler(),
        BalancedRandomForestClassifier(n_estimators=100, sampling_strategy='auto', random_state=42, n_jobs=-1)
    ),
    "XGBoost": make_pipeline(
        StandardScaler(),
        XGBClassifier(scale_pos_weight=scale_weight, eval_metric='logloss', random_state=42, n_jobs=-1)
    ),
    "Random Forest": RandomForestClassifier(
        class_weight="balanced", n_estimators=100, random_state=RANDOM_STATE, n_jobs=-1
    ), 
}

agg_strategies = {
    "Mean": "mean",
    "Median": "median",
    "Max": "max",
    "75th_Percentile": lambda x: np.percentile(x, 75)
}

cv_train = StratifiedGroupKFold(n_splits=3, shuffle=True, random_state=42)
results_list = []


for model_name, model in models.items():
    
    # Train and predict
    model.fit(X_train, y_train)
    test_probs = model.predict_proba(X_test)[:, 1]
    
    # Out-of-fold probabilities for unbiased threshold tuning
    train_unbiased_probs = cross_val_predict(
        model, X_train, y_train, 
        groups=groups.iloc[train_idx], 
        cv=cv_train, 
        method='predict_proba',
        n_jobs=-1
    )[:, 1]
    
    train_base_df = pd.DataFrame({
        "subject_activity": groups.iloc[train_idx].values,
        "true_label": y_train.values,
        "pred_prob": train_unbiased_probs 
    })
    
    test_base_df = pd.DataFrame({
        "subject_activity": groups.iloc[test_idx].values,
        "true_label": y_test.values,
        "pred_prob": test_probs 
    })

    # Test Aggregation Strategies
    for strategy_name, agg_func in agg_strategies.items():
        
        train_agg = train_base_df.groupby("subject_activity").agg(
            true_label=("true_label", "first"),
            agg_prob=("pred_prob", agg_func)
        ).reset_index()
        
        best_thresh = 0.5
        best_b_acc = 0
        for thresh in np.arange(0.1, 0.9, 0.02):
            train_preds = (train_agg["agg_prob"] >= thresh).astype(int)
            b_acc = balanced_accuracy_score(train_agg["true_label"], train_preds)
            if b_acc >= best_b_acc: 
                best_b_acc = b_acc
                best_thresh = thresh
                
        test_agg = test_base_df.groupby("subject_activity").agg(
            true_label=("true_label", "first"),
            agg_prob=("pred_prob", agg_func)
        ).reset_index()
        
        test_preds = (test_agg["agg_prob"] >= best_thresh).astype(int)
        final_b_acc = balanced_accuracy_score(test_agg["true_label"], test_preds)
        acc = accuracy_score(test_agg["true_label"], test_preds)
        f1 = f1_score(test_agg["true_label"], test_preds)
        recall_0 = recall_score(test_agg["true_label"], test_preds, pos_label=0, zero_division=0)
        recall_1 = recall_score(test_agg["true_label"], test_preds, pos_label=1, zero_division=0)
        precision = precision_score(test_agg["true_label"], test_preds)
        
        results_list.append({
            "Model": model_name,
            "Strategy": strategy_name,
            "Thresh": round(best_thresh, 2),
            "Bal_Acc": round(final_b_acc, 4),
            "Accuracy": round(acc, 2),
            "F1": round(f1, 2),
            "Rec_Relaxed": round(recall_0, 2),
            "Rec_Stress": round(recall_1, 2),
            "Precision": round(precision, 2)
        })

comparison_df = pd.DataFrame(results_list)
comparison_df = comparison_df.sort_values(by="Bal_Acc", ascending=False).reset_index(drop=True)

print("\n=== AST Results ===")
print(comparison_df.to_string(index=False))

=== AST Results ===
                 Model        Strategy  Thresh  Bal_Acc  Accuracy   F1  Rec_Relaxed  Rec_Stress  Precision
Balanced Random Forest            Mean    0.48   0.6126      0.63 0.72         0.57        0.65       0.79
         Random Forest             Max    0.82   0.5934      0.60 0.69         0.57        0.62       0.78
               XGBoost            Mean    0.80   0.5842      0.63 0.73         0.48        0.69       0.77
               XGBoost          Median    0.86   0.5842      0.63 0.73         0.48        0.69       0.77
               XGBoost 75th_Percentile    0.86   0.5705      0.67 0.78         0.33        0.81       0.75
         Random Forest            Mean    0.70   0.5559      0.63 0.74         0.38        0.73       0.75
Balanced Random Forest             Max    0.60   0.5549      0.55 0.63         0.57        0.54       0.76
Balanced Random Forest          Median    0.44   0.5417      0.63 0.74         0.33        0.75       0.74
   Logistic Regression             Max    0.74   0.5380      0.73 0.84         0.10        0.98       0.73
Balanced Random Forest 75th_Percentile    0.52   0.5362      0.56 0.66         0.48        0.60       0.74
         Random Forest 75th_Percentile    0.74   0.5321      0.62 0.73         0.33        0.73       0.73
         Random Forest          Median    0.70   0.5321      0.62 0.73         0.33        0.73       0.73
               XGBoost             Max    0.66   0.5238      0.73 0.84         0.05        1.00       0.72
   Logistic Regression            Mean    0.72   0.5023      0.49 0.57         0.52        0.48       0.71
   Logistic Regression          Median    0.82   0.4982      0.55 0.66         0.38        0.62       0.71
   Logistic Regression 75th_Percentile    0.88   0.4940      0.60 0.73         0.24        0.75       0.71